// WARNING: This file is machine generated by fidlgen.

#include <fidl/fuchsia.net.name/cpp/natural_types.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wshadow"

void fidl::internal::NaturalCodingTraits<::fuchsia_net_name::LookupError, ::fidl::internal::NaturalCodingConstraintEmpty>::Encode(
    fidl::internal::NaturalEncoder* encoder, ::fuchsia_net_name::LookupError* value, size_t offset, size_t recursion_depth) {
  switch (*value) {
    case ::fuchsia_net_name::LookupError::kNotFound:
    case ::fuchsia_net_name::LookupError::kTransient:
    case ::fuchsia_net_name::LookupError::kInvalidArgs:
    case ::fuchsia_net_name::LookupError::kInternalError:
      break;
    default:
      encoder->SetError(::fidl::internal::kCodingErrorUnknownEnumValue);
      return;
  }
  *encoder->template GetPtr<::fuchsia_net_name::LookupError>(offset) = *value;
}

void fidl::internal::NaturalCodingTraits<::fuchsia_net_name::LookupError, ::fidl::internal::NaturalCodingConstraintEmpty>::Decode(
    fidl::internal::NaturalDecoder* decoder, ::fuchsia_net_name::LookupError* value, size_t offset, size_t recursion_depth) {
  *value = *decoder->template GetPtr<::fuchsia_net_name::LookupError>(offset);
  switch (*value) {
    case ::fuchsia_net_name::LookupError::kNotFound:
    case ::fuchsia_net_name::LookupError::kTransient:
    case ::fuchsia_net_name::LookupError::kInvalidArgs:
    case ::fuchsia_net_name::LookupError::kInternalError:
      break;
    default:
      decoder->SetError(::fidl::internal::kCodingErrorUnknownEnumValue);
      return;
  }
}

::fuchsia_net_name::LookupLookupIpRequest::LookupLookupIpRequest(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_net_name::LookupLookupIpRequest::LookupLookupIpRequest(::std::string hostname, ::fuchsia_net_name::LookupIpOptions options) noexcept
    : storage_({.hostname = std::move(hostname),
                .options = std::move(options)}) {}

::fuchsia_net_name::LookupLookupIpRequest::LookupLookupIpRequest(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LookupLookupIpRequest(Storage_{
                                                                                                                                   .hostname = {},
                                                                                                                                   .options = ::fidl::internal::DefaultConstructPossiblyInvalidObjectTag{},
                                                                                                                               }) {}
::fuchsia_net_name::LookupLookupIpRequest::LookupLookupIpRequest(const ::fuchsia_net_name::LookupLookupIpRequest& other) noexcept : ::fuchsia_net_name::LookupLookupIpRequest(other.CloneStorage_()) {}

::fuchsia_net_name::LookupLookupIpRequest& fuchsia_net_name::LookupLookupIpRequest::operator=(const ::fuchsia_net_name::LookupLookupIpRequest& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::LookupLookupIpRequest::operator==(const LookupLookupIpRequest& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupLookupIpRequest, 32>::Equal(this, &other);
}

bool fuchsia_net_name::LookupLookupIpRequest::operator!=(const LookupLookupIpRequest& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupLookupIpRequest, 32>::Equal(this, &other);
}

::fuchsia_net_name::LookupLookupIpRequest::Storage_ fuchsia_net_name::LookupLookupIpRequest::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.hostname),
      ::fidl::internal::NaturalClone(storage_.options)};
}
const ::std::string&
fuchsia_net_name::LookupLookupIpRequest::hostname() const {
  return storage_.hostname;
}

::std::string& ::fuchsia_net_name::LookupLookupIpRequest::hostname() {
  return storage_.hostname;
}

::fuchsia_net_name::LookupLookupIpRequest& ::fuchsia_net_name::LookupLookupIpRequest::hostname(::std::string value) {
  storage_.hostname = std::move(value);
  return *this;
}
const ::fuchsia_net_name::LookupIpOptions&
fuchsia_net_name::LookupLookupIpRequest::options() const {
  return storage_.options;
}

::fuchsia_net_name::LookupIpOptions& ::fuchsia_net_name::LookupLookupIpRequest::options() {
  return storage_.options;
}

::fuchsia_net_name::LookupLookupIpRequest& ::fuchsia_net_name::LookupLookupIpRequest::options(::fuchsia_net_name::LookupIpOptions value) {
  storage_.options = std::move(value);
  return *this;
}

::fuchsia_net_name::LookupLookupIpResponse::LookupLookupIpResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_net_name::LookupLookupIpResponse::LookupLookupIpResponse(::fuchsia_net_name::LookupResult result) noexcept
    : storage_({.result = std::move(result)}) {}

::fuchsia_net_name::LookupLookupIpResponse::LookupLookupIpResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LookupLookupIpResponse(Storage_{
                                                                                                                                     .result = ::fidl::internal::DefaultConstructPossiblyInvalidObjectTag{},
                                                                                                                                 }) {}
::fuchsia_net_name::LookupLookupIpResponse::LookupLookupIpResponse(const ::fuchsia_net_name::LookupLookupIpResponse& other) noexcept : ::fuchsia_net_name::LookupLookupIpResponse(other.CloneStorage_()) {}

::fuchsia_net_name::LookupLookupIpResponse& fuchsia_net_name::LookupLookupIpResponse::operator=(const ::fuchsia_net_name::LookupLookupIpResponse& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::LookupLookupIpResponse::operator==(const LookupLookupIpResponse& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupLookupIpResponse, 16>::Equal(this, &other);
}

bool fuchsia_net_name::LookupLookupIpResponse::operator!=(const LookupLookupIpResponse& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupLookupIpResponse, 16>::Equal(this, &other);
}

::fuchsia_net_name::LookupLookupIpResponse::Storage_ fuchsia_net_name::LookupLookupIpResponse::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.result)};
}
const ::fuchsia_net_name::LookupResult&
fuchsia_net_name::LookupLookupIpResponse::result() const {
  return storage_.result;
}

::fuchsia_net_name::LookupResult& ::fuchsia_net_name::LookupLookupIpResponse::result() {
  return storage_.result;
}

::fuchsia_net_name::LookupLookupIpResponse& ::fuchsia_net_name::LookupLookupIpResponse::result(::fuchsia_net_name::LookupResult value) {
  storage_.result = std::move(value);
  return *this;
}

::fuchsia_net_name::LookupLookupHostnameRequest::LookupLookupHostnameRequest(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_net_name::LookupLookupHostnameRequest::LookupLookupHostnameRequest(::fuchsia_net::IpAddress addr) noexcept
    : storage_({.addr = std::move(addr)}) {}

::fuchsia_net_name::LookupLookupHostnameRequest::LookupLookupHostnameRequest(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LookupLookupHostnameRequest(Storage_{
                                                                                                                                               .addr = ::fidl::internal::DefaultConstructPossiblyInvalidObjectTag{},
                                                                                                                                           }) {}
::fuchsia_net_name::LookupLookupHostnameRequest::LookupLookupHostnameRequest(const ::fuchsia_net_name::LookupLookupHostnameRequest& other) noexcept : ::fuchsia_net_name::LookupLookupHostnameRequest(other.CloneStorage_()) {}

::fuchsia_net_name::LookupLookupHostnameRequest& fuchsia_net_name::LookupLookupHostnameRequest::operator=(const ::fuchsia_net_name::LookupLookupHostnameRequest& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::LookupLookupHostnameRequest::operator==(const LookupLookupHostnameRequest& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupLookupHostnameRequest, 16>::Equal(this, &other);
}

bool fuchsia_net_name::LookupLookupHostnameRequest::operator!=(const LookupLookupHostnameRequest& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupLookupHostnameRequest, 16>::Equal(this, &other);
}

::fuchsia_net_name::LookupLookupHostnameRequest::Storage_ fuchsia_net_name::LookupLookupHostnameRequest::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.addr)};
}
const ::fuchsia_net::IpAddress&
fuchsia_net_name::LookupLookupHostnameRequest::addr() const {
  return storage_.addr;
}

::fuchsia_net::IpAddress& ::fuchsia_net_name::LookupLookupHostnameRequest::addr() {
  return storage_.addr;
}

::fuchsia_net_name::LookupLookupHostnameRequest& ::fuchsia_net_name::LookupLookupHostnameRequest::addr(::fuchsia_net::IpAddress value) {
  storage_.addr = std::move(value);
  return *this;
}

::fuchsia_net_name::LookupLookupHostnameResponse::LookupLookupHostnameResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_net_name::LookupLookupHostnameResponse::LookupLookupHostnameResponse(::std::string hostname) noexcept
    : storage_({.hostname = std::move(hostname)}) {}

::fuchsia_net_name::LookupLookupHostnameResponse::LookupLookupHostnameResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LookupLookupHostnameResponse(Storage_{
                                                                                                                                                 .hostname = {},
                                                                                                                                             }) {}
::fuchsia_net_name::LookupLookupHostnameResponse::LookupLookupHostnameResponse(const ::fuchsia_net_name::LookupLookupHostnameResponse& other) noexcept : ::fuchsia_net_name::LookupLookupHostnameResponse(other.CloneStorage_()) {}

::fuchsia_net_name::LookupLookupHostnameResponse& fuchsia_net_name::LookupLookupHostnameResponse::operator=(const ::fuchsia_net_name::LookupLookupHostnameResponse& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::LookupLookupHostnameResponse::operator==(const LookupLookupHostnameResponse& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupLookupHostnameResponse, 16>::Equal(this, &other);
}

bool fuchsia_net_name::LookupLookupHostnameResponse::operator!=(const LookupLookupHostnameResponse& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupLookupHostnameResponse, 16>::Equal(this, &other);
}

::fuchsia_net_name::LookupLookupHostnameResponse::Storage_ fuchsia_net_name::LookupLookupHostnameResponse::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.hostname)};
}
const ::std::string&
fuchsia_net_name::LookupLookupHostnameResponse::hostname() const {
  return storage_.hostname;
}

::std::string& ::fuchsia_net_name::LookupLookupHostnameResponse::hostname() {
  return storage_.hostname;
}

::fuchsia_net_name::LookupLookupHostnameResponse& ::fuchsia_net_name::LookupLookupHostnameResponse::hostname(::std::string value) {
  storage_.hostname = std::move(value);
  return *this;
}

::fuchsia_net_name::LookupAdminSetDnsServersRequest::LookupAdminSetDnsServersRequest(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_net_name::LookupAdminSetDnsServersRequest::LookupAdminSetDnsServersRequest(::std::vector<::fuchsia_net::SocketAddress> servers) noexcept
    : storage_({.servers = std::move(servers)}) {}

::fuchsia_net_name::LookupAdminSetDnsServersRequest::LookupAdminSetDnsServersRequest(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LookupAdminSetDnsServersRequest(Storage_{
                                                                                                                                                       .servers = {},
                                                                                                                                                   }) {}
::fuchsia_net_name::LookupAdminSetDnsServersRequest::LookupAdminSetDnsServersRequest(const ::fuchsia_net_name::LookupAdminSetDnsServersRequest& other) noexcept : ::fuchsia_net_name::LookupAdminSetDnsServersRequest(other.CloneStorage_()) {}

::fuchsia_net_name::LookupAdminSetDnsServersRequest& fuchsia_net_name::LookupAdminSetDnsServersRequest::operator=(const ::fuchsia_net_name::LookupAdminSetDnsServersRequest& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::LookupAdminSetDnsServersRequest::operator==(const LookupAdminSetDnsServersRequest& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupAdminSetDnsServersRequest, 16>::Equal(this, &other);
}

bool fuchsia_net_name::LookupAdminSetDnsServersRequest::operator!=(const LookupAdminSetDnsServersRequest& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupAdminSetDnsServersRequest, 16>::Equal(this, &other);
}

::fuchsia_net_name::LookupAdminSetDnsServersRequest::Storage_ fuchsia_net_name::LookupAdminSetDnsServersRequest::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.servers)};
}
const ::std::vector<::fuchsia_net::SocketAddress>&
fuchsia_net_name::LookupAdminSetDnsServersRequest::servers() const {
  return storage_.servers;
}

::std::vector<::fuchsia_net::SocketAddress>& ::fuchsia_net_name::LookupAdminSetDnsServersRequest::servers() {
  return storage_.servers;
}

::fuchsia_net_name::LookupAdminSetDnsServersRequest& ::fuchsia_net_name::LookupAdminSetDnsServersRequest::servers(::std::vector<::fuchsia_net::SocketAddress> value) {
  storage_.servers = std::move(value);
  return *this;
}

::fuchsia_net_name::LookupAdminSetDnsServersResponse::LookupAdminSetDnsServersResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_net_name::LookupAdminSetDnsServersResponse::LookupAdminSetDnsServersResponse(uint8_t __reserved) noexcept
    : storage_({.__reserved = std::move(__reserved)}) {}

::fuchsia_net_name::LookupAdminSetDnsServersResponse::LookupAdminSetDnsServersResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LookupAdminSetDnsServersResponse(Storage_{
                                                                                                                                                         .__reserved = 0u,
                                                                                                                                                     }) {}
::fuchsia_net_name::LookupAdminSetDnsServersResponse::LookupAdminSetDnsServersResponse(const ::fuchsia_net_name::LookupAdminSetDnsServersResponse& other) noexcept : ::fuchsia_net_name::LookupAdminSetDnsServersResponse(other.CloneStorage_()) {}

::fuchsia_net_name::LookupAdminSetDnsServersResponse& fuchsia_net_name::LookupAdminSetDnsServersResponse::operator=(const ::fuchsia_net_name::LookupAdminSetDnsServersResponse& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::LookupAdminSetDnsServersResponse::operator==(const LookupAdminSetDnsServersResponse& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupAdminSetDnsServersResponse, 1>::Equal(this, &other);
}

bool fuchsia_net_name::LookupAdminSetDnsServersResponse::operator!=(const LookupAdminSetDnsServersResponse& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupAdminSetDnsServersResponse, 1>::Equal(this, &other);
}

::fuchsia_net_name::LookupAdminSetDnsServersResponse::Storage_ fuchsia_net_name::LookupAdminSetDnsServersResponse::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.__reserved)};
}
uint8_t
fuchsia_net_name::LookupAdminSetDnsServersResponse::__reserved() const {
  return storage_.__reserved;
}

uint8_t& ::fuchsia_net_name::LookupAdminSetDnsServersResponse::__reserved() {
  return storage_.__reserved;
}

::fuchsia_net_name::LookupAdminSetDnsServersResponse& ::fuchsia_net_name::LookupAdminSetDnsServersResponse::__reserved(uint8_t value) {
  storage_.__reserved = std::move(value);
  return *this;
}

::fuchsia_net_name::LookupAdminGetDnsServersResponse::LookupAdminGetDnsServersResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_net_name::LookupAdminGetDnsServersResponse::LookupAdminGetDnsServersResponse(::std::vector<::fuchsia_net::SocketAddress> servers) noexcept
    : storage_({.servers = std::move(servers)}) {}

::fuchsia_net_name::LookupAdminGetDnsServersResponse::LookupAdminGetDnsServersResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LookupAdminGetDnsServersResponse(Storage_{
                                                                                                                                                         .servers = {},
                                                                                                                                                     }) {}
::fuchsia_net_name::LookupAdminGetDnsServersResponse::LookupAdminGetDnsServersResponse(const ::fuchsia_net_name::LookupAdminGetDnsServersResponse& other) noexcept : ::fuchsia_net_name::LookupAdminGetDnsServersResponse(other.CloneStorage_()) {}

::fuchsia_net_name::LookupAdminGetDnsServersResponse& fuchsia_net_name::LookupAdminGetDnsServersResponse::operator=(const ::fuchsia_net_name::LookupAdminGetDnsServersResponse& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::LookupAdminGetDnsServersResponse::operator==(const LookupAdminGetDnsServersResponse& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupAdminGetDnsServersResponse, 16>::Equal(this, &other);
}

bool fuchsia_net_name::LookupAdminGetDnsServersResponse::operator!=(const LookupAdminGetDnsServersResponse& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::LookupAdminGetDnsServersResponse, 16>::Equal(this, &other);
}

::fuchsia_net_name::LookupAdminGetDnsServersResponse::Storage_ fuchsia_net_name::LookupAdminGetDnsServersResponse::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.servers)};
}
const ::std::vector<::fuchsia_net::SocketAddress>&
fuchsia_net_name::LookupAdminGetDnsServersResponse::servers() const {
  return storage_.servers;
}

::std::vector<::fuchsia_net::SocketAddress>& ::fuchsia_net_name::LookupAdminGetDnsServersResponse::servers() {
  return storage_.servers;
}

::fuchsia_net_name::LookupAdminGetDnsServersResponse& ::fuchsia_net_name::LookupAdminGetDnsServersResponse::servers(::std::vector<::fuchsia_net::SocketAddress> value) {
  storage_.servers = std::move(value);
  return *this;
}

::fuchsia_net_name::DnsServerWatcherWatchServersResponse::DnsServerWatcherWatchServersResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_net_name::DnsServerWatcherWatchServersResponse::DnsServerWatcherWatchServersResponse(::std::vector<::fuchsia_net_name::DnsServer> servers) noexcept
    : storage_({.servers = std::move(servers)}) {}

::fuchsia_net_name::DnsServerWatcherWatchServersResponse::DnsServerWatcherWatchServersResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : DnsServerWatcherWatchServersResponse(Storage_{
                                                                                                                                                                 .servers = {},
                                                                                                                                                             }) {}
::fuchsia_net_name::DnsServerWatcherWatchServersResponse::DnsServerWatcherWatchServersResponse(const ::fuchsia_net_name::DnsServerWatcherWatchServersResponse& other) noexcept : ::fuchsia_net_name::DnsServerWatcherWatchServersResponse(other.CloneStorage_()) {}

::fuchsia_net_name::DnsServerWatcherWatchServersResponse& fuchsia_net_name::DnsServerWatcherWatchServersResponse::operator=(const ::fuchsia_net_name::DnsServerWatcherWatchServersResponse& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::DnsServerWatcherWatchServersResponse::operator==(const DnsServerWatcherWatchServersResponse& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::DnsServerWatcherWatchServersResponse, 16>::Equal(this, &other);
}

bool fuchsia_net_name::DnsServerWatcherWatchServersResponse::operator!=(const DnsServerWatcherWatchServersResponse& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_net_name::DnsServerWatcherWatchServersResponse, 16>::Equal(this, &other);
}

::fuchsia_net_name::DnsServerWatcherWatchServersResponse::Storage_ fuchsia_net_name::DnsServerWatcherWatchServersResponse::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.servers)};
}
const ::std::vector<::fuchsia_net_name::DnsServer>&
fuchsia_net_name::DnsServerWatcherWatchServersResponse::servers() const {
  return storage_.servers;
}

::std::vector<::fuchsia_net_name::DnsServer>& ::fuchsia_net_name::DnsServerWatcherWatchServersResponse::servers() {
  return storage_.servers;
}

::fuchsia_net_name::DnsServerWatcherWatchServersResponse& ::fuchsia_net_name::DnsServerWatcherWatchServersResponse::servers(::std::vector<::fuchsia_net_name::DnsServer> value) {
  storage_.servers = std::move(value);
  return *this;
}

::fuchsia_net_name::StaticDnsServerSource::StaticDnsServerSource(::fuchsia_net_name::StaticDnsServerSource::Storage_ storage) noexcept : storage_(std::move(storage)) {}

::fuchsia_net_name::StaticDnsServerSource::StaticDnsServerSource(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : StaticDnsServerSource(Storage_{}) {}

::fuchsia_net_name::StaticDnsServerSource::StaticDnsServerSource(const ::fuchsia_net_name::StaticDnsServerSource& other) noexcept : StaticDnsServerSource(other.CloneStorage_()) {}

::fuchsia_net_name::StaticDnsServerSource& ::fuchsia_net_name::StaticDnsServerSource::operator=(const ::fuchsia_net_name::StaticDnsServerSource& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::StaticDnsServerSource::operator==(const StaticDnsServerSource& other) const noexcept {
  return ::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::StaticDnsServerSource>::Equal(this, &other);
}
bool fuchsia_net_name::StaticDnsServerSource::operator!=(const StaticDnsServerSource& other) const noexcept {
  return !::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::StaticDnsServerSource>::Equal(this, &other);
}

::fuchsia_net_name::StaticDnsServerSource::Storage_ fuchsia_net_name::StaticDnsServerSource::CloneStorage_() const {
  return Storage_{};
}

bool fuchsia_net_name::StaticDnsServerSource::IsEmpty() const {
  return true;
}

::fuchsia_net_name::DhcpDnsServerSource::DhcpDnsServerSource(::fuchsia_net_name::DhcpDnsServerSource::Storage_ storage) noexcept : storage_(std::move(storage)) {}

::fuchsia_net_name::DhcpDnsServerSource::DhcpDnsServerSource(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : DhcpDnsServerSource(Storage_{}) {}

::fuchsia_net_name::DhcpDnsServerSource::DhcpDnsServerSource(const ::fuchsia_net_name::DhcpDnsServerSource& other) noexcept : DhcpDnsServerSource(other.CloneStorage_()) {}

::fuchsia_net_name::DhcpDnsServerSource& ::fuchsia_net_name::DhcpDnsServerSource::operator=(const ::fuchsia_net_name::DhcpDnsServerSource& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::DhcpDnsServerSource::operator==(const DhcpDnsServerSource& other) const noexcept {
  return ::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::DhcpDnsServerSource>::Equal(this, &other);
}
bool fuchsia_net_name::DhcpDnsServerSource::operator!=(const DhcpDnsServerSource& other) const noexcept {
  return !::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::DhcpDnsServerSource>::Equal(this, &other);
}

::fuchsia_net_name::DhcpDnsServerSource::Storage_ fuchsia_net_name::DhcpDnsServerSource::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.source_interface)};
}

bool fuchsia_net_name::DhcpDnsServerSource::IsEmpty() const {
  return !(storage_.source_interface.has_value());
}
const std::optional<uint64_t>& fuchsia_net_name::DhcpDnsServerSource::source_interface() const {
  return storage_.source_interface;
}

::std::optional<uint64_t>& fuchsia_net_name::DhcpDnsServerSource::source_interface() {
  return storage_.source_interface;
}

::fuchsia_net_name::DhcpDnsServerSource& fuchsia_net_name::DhcpDnsServerSource::source_interface(std::optional<uint64_t> value) {
  storage_.source_interface = std::move(value);
  return *this;
}

::fuchsia_net_name::NdpDnsServerSource::NdpDnsServerSource(::fuchsia_net_name::NdpDnsServerSource::Storage_ storage) noexcept : storage_(std::move(storage)) {}

::fuchsia_net_name::NdpDnsServerSource::NdpDnsServerSource(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : NdpDnsServerSource(Storage_{}) {}

::fuchsia_net_name::NdpDnsServerSource::NdpDnsServerSource(const ::fuchsia_net_name::NdpDnsServerSource& other) noexcept : NdpDnsServerSource(other.CloneStorage_()) {}

::fuchsia_net_name::NdpDnsServerSource& ::fuchsia_net_name::NdpDnsServerSource::operator=(const ::fuchsia_net_name::NdpDnsServerSource& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::NdpDnsServerSource::operator==(const NdpDnsServerSource& other) const noexcept {
  return ::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::NdpDnsServerSource>::Equal(this, &other);
}
bool fuchsia_net_name::NdpDnsServerSource::operator!=(const NdpDnsServerSource& other) const noexcept {
  return !::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::NdpDnsServerSource>::Equal(this, &other);
}

::fuchsia_net_name::NdpDnsServerSource::Storage_ fuchsia_net_name::NdpDnsServerSource::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.source_interface)};
}

bool fuchsia_net_name::NdpDnsServerSource::IsEmpty() const {
  return !(storage_.source_interface.has_value());
}
const std::optional<uint64_t>& fuchsia_net_name::NdpDnsServerSource::source_interface() const {
  return storage_.source_interface;
}

::std::optional<uint64_t>& fuchsia_net_name::NdpDnsServerSource::source_interface() {
  return storage_.source_interface;
}

::fuchsia_net_name::NdpDnsServerSource& fuchsia_net_name::NdpDnsServerSource::source_interface(std::optional<uint64_t> value) {
  storage_.source_interface = std::move(value);
  return *this;
}

::fuchsia_net_name::Dhcpv6DnsServerSource::Dhcpv6DnsServerSource(::fuchsia_net_name::Dhcpv6DnsServerSource::Storage_ storage) noexcept : storage_(std::move(storage)) {}

::fuchsia_net_name::Dhcpv6DnsServerSource::Dhcpv6DnsServerSource(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : Dhcpv6DnsServerSource(Storage_{}) {}

::fuchsia_net_name::Dhcpv6DnsServerSource::Dhcpv6DnsServerSource(const ::fuchsia_net_name::Dhcpv6DnsServerSource& other) noexcept : Dhcpv6DnsServerSource(other.CloneStorage_()) {}

::fuchsia_net_name::Dhcpv6DnsServerSource& ::fuchsia_net_name::Dhcpv6DnsServerSource::operator=(const ::fuchsia_net_name::Dhcpv6DnsServerSource& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::Dhcpv6DnsServerSource::operator==(const Dhcpv6DnsServerSource& other) const noexcept {
  return ::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::Dhcpv6DnsServerSource>::Equal(this, &other);
}
bool fuchsia_net_name::Dhcpv6DnsServerSource::operator!=(const Dhcpv6DnsServerSource& other) const noexcept {
  return !::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::Dhcpv6DnsServerSource>::Equal(this, &other);
}

::fuchsia_net_name::Dhcpv6DnsServerSource::Storage_ fuchsia_net_name::Dhcpv6DnsServerSource::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.source_interface)};
}

bool fuchsia_net_name::Dhcpv6DnsServerSource::IsEmpty() const {
  return !(storage_.source_interface.has_value());
}
const std::optional<uint64_t>& fuchsia_net_name::Dhcpv6DnsServerSource::source_interface() const {
  return storage_.source_interface;
}

::std::optional<uint64_t>& fuchsia_net_name::Dhcpv6DnsServerSource::source_interface() {
  return storage_.source_interface;
}

::fuchsia_net_name::Dhcpv6DnsServerSource& fuchsia_net_name::Dhcpv6DnsServerSource::source_interface(std::optional<uint64_t> value) {
  storage_.source_interface = std::move(value);
  return *this;
}

::fuchsia_net_name::SocketProxyDnsServerSource::SocketProxyDnsServerSource(::fuchsia_net_name::SocketProxyDnsServerSource::Storage_ storage) noexcept : storage_(std::move(storage)) {}

::fuchsia_net_name::SocketProxyDnsServerSource::SocketProxyDnsServerSource(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : SocketProxyDnsServerSource(Storage_{}) {}

::fuchsia_net_name::SocketProxyDnsServerSource::SocketProxyDnsServerSource(const ::fuchsia_net_name::SocketProxyDnsServerSource& other) noexcept : SocketProxyDnsServerSource(other.CloneStorage_()) {}

::fuchsia_net_name::SocketProxyDnsServerSource& ::fuchsia_net_name::SocketProxyDnsServerSource::operator=(const ::fuchsia_net_name::SocketProxyDnsServerSource& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::SocketProxyDnsServerSource::operator==(const SocketProxyDnsServerSource& other) const noexcept {
  return ::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::SocketProxyDnsServerSource>::Equal(this, &other);
}
bool fuchsia_net_name::SocketProxyDnsServerSource::operator!=(const SocketProxyDnsServerSource& other) const noexcept {
  return !::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::SocketProxyDnsServerSource>::Equal(this, &other);
}

::fuchsia_net_name::SocketProxyDnsServerSource::Storage_ fuchsia_net_name::SocketProxyDnsServerSource::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.source_interface)};
}

bool fuchsia_net_name::SocketProxyDnsServerSource::IsEmpty() const {
  return !(storage_.source_interface.has_value());
}
const std::optional<uint64_t>& fuchsia_net_name::SocketProxyDnsServerSource::source_interface() const {
  return storage_.source_interface;
}

::std::optional<uint64_t>& fuchsia_net_name::SocketProxyDnsServerSource::source_interface() {
  return storage_.source_interface;
}

::fuchsia_net_name::SocketProxyDnsServerSource& fuchsia_net_name::SocketProxyDnsServerSource::source_interface(std::optional<uint64_t> value) {
  storage_.source_interface = std::move(value);
  return *this;
}

::fuchsia_net_name::DnsServer::DnsServer(::fuchsia_net_name::DnsServer::Storage_ storage) noexcept : storage_(std::move(storage)) {}

::fuchsia_net_name::DnsServer::DnsServer(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : DnsServer(Storage_{}) {}

::fuchsia_net_name::DnsServer::DnsServer(const ::fuchsia_net_name::DnsServer& other) noexcept : DnsServer(other.CloneStorage_()) {}

::fuchsia_net_name::DnsServer& ::fuchsia_net_name::DnsServer::operator=(const ::fuchsia_net_name::DnsServer& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::DnsServer::operator==(const DnsServer& other) const noexcept {
  return ::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::DnsServer>::Equal(this, &other);
}
bool fuchsia_net_name::DnsServer::operator!=(const DnsServer& other) const noexcept {
  return !::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::DnsServer>::Equal(this, &other);
}

::fuchsia_net_name::DnsServer::Storage_ fuchsia_net_name::DnsServer::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.address),
      ::fidl::internal::NaturalClone(storage_.source)};
}

bool fuchsia_net_name::DnsServer::IsEmpty() const {
  return !(storage_.address.has_value() || storage_.source.has_value());
}
const std::optional<::fuchsia_net::SocketAddress>& fuchsia_net_name::DnsServer::address() const {
  return storage_.address;
}

::std::optional<::fuchsia_net::SocketAddress>& fuchsia_net_name::DnsServer::address() {
  return storage_.address;
}

::fuchsia_net_name::DnsServer& fuchsia_net_name::DnsServer::address(std::optional<::fuchsia_net::SocketAddress> value) {
  storage_.address = std::move(value);
  return *this;
}
const std::optional<::fuchsia_net_name::DnsServerSource>& fuchsia_net_name::DnsServer::source() const {
  return storage_.source;
}

::std::optional<::fuchsia_net_name::DnsServerSource>& fuchsia_net_name::DnsServer::source() {
  return storage_.source;
}

::fuchsia_net_name::DnsServer& fuchsia_net_name::DnsServer::source(std::optional<::fuchsia_net_name::DnsServerSource> value) {
  storage_.source = std::move(value);
  return *this;
}

::fuchsia_net_name::LookupIpOptions::LookupIpOptions(::fuchsia_net_name::LookupIpOptions::Storage_ storage) noexcept : storage_(std::move(storage)) {}

::fuchsia_net_name::LookupIpOptions::LookupIpOptions(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LookupIpOptions(Storage_{}) {}

::fuchsia_net_name::LookupIpOptions::LookupIpOptions(const ::fuchsia_net_name::LookupIpOptions& other) noexcept : LookupIpOptions(other.CloneStorage_()) {}

::fuchsia_net_name::LookupIpOptions& ::fuchsia_net_name::LookupIpOptions::operator=(const ::fuchsia_net_name::LookupIpOptions& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::LookupIpOptions::operator==(const LookupIpOptions& other) const noexcept {
  return ::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::LookupIpOptions>::Equal(this, &other);
}
bool fuchsia_net_name::LookupIpOptions::operator!=(const LookupIpOptions& other) const noexcept {
  return !::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::LookupIpOptions>::Equal(this, &other);
}

::fuchsia_net_name::LookupIpOptions::Storage_ fuchsia_net_name::LookupIpOptions::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.ipv4_lookup),
      ::fidl::internal::NaturalClone(storage_.ipv6_lookup),
      ::fidl::internal::NaturalClone(storage_.sort_addresses),
      ::fidl::internal::NaturalClone(storage_.canonical_name_lookup)};
}

bool fuchsia_net_name::LookupIpOptions::IsEmpty() const {
  return !(storage_.ipv4_lookup.has_value() || storage_.ipv6_lookup.has_value() || storage_.sort_addresses.has_value() || storage_.canonical_name_lookup.has_value());
}
const std::optional<bool>& fuchsia_net_name::LookupIpOptions::ipv4_lookup() const {
  return storage_.ipv4_lookup;
}

::std::optional<bool>& fuchsia_net_name::LookupIpOptions::ipv4_lookup() {
  return storage_.ipv4_lookup;
}

::fuchsia_net_name::LookupIpOptions& fuchsia_net_name::LookupIpOptions::ipv4_lookup(std::optional<bool> value) {
  storage_.ipv4_lookup = std::move(value);
  return *this;
}
const std::optional<bool>& fuchsia_net_name::LookupIpOptions::ipv6_lookup() const {
  return storage_.ipv6_lookup;
}

::std::optional<bool>& fuchsia_net_name::LookupIpOptions::ipv6_lookup() {
  return storage_.ipv6_lookup;
}

::fuchsia_net_name::LookupIpOptions& fuchsia_net_name::LookupIpOptions::ipv6_lookup(std::optional<bool> value) {
  storage_.ipv6_lookup = std::move(value);
  return *this;
}
const std::optional<bool>& fuchsia_net_name::LookupIpOptions::sort_addresses() const {
  return storage_.sort_addresses;
}

::std::optional<bool>& fuchsia_net_name::LookupIpOptions::sort_addresses() {
  return storage_.sort_addresses;
}

::fuchsia_net_name::LookupIpOptions& fuchsia_net_name::LookupIpOptions::sort_addresses(std::optional<bool> value) {
  storage_.sort_addresses = std::move(value);
  return *this;
}
const std::optional<bool>& fuchsia_net_name::LookupIpOptions::canonical_name_lookup() const {
  return storage_.canonical_name_lookup;
}

::std::optional<bool>& fuchsia_net_name::LookupIpOptions::canonical_name_lookup() {
  return storage_.canonical_name_lookup;
}

::fuchsia_net_name::LookupIpOptions& fuchsia_net_name::LookupIpOptions::canonical_name_lookup(std::optional<bool> value) {
  storage_.canonical_name_lookup = std::move(value);
  return *this;
}

::fuchsia_net_name::LookupResult::LookupResult(::fuchsia_net_name::LookupResult::Storage_ storage) noexcept : storage_(std::move(storage)) {}

::fuchsia_net_name::LookupResult::LookupResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LookupResult(Storage_{}) {}

::fuchsia_net_name::LookupResult::LookupResult(const ::fuchsia_net_name::LookupResult& other) noexcept : LookupResult(other.CloneStorage_()) {}

::fuchsia_net_name::LookupResult& ::fuchsia_net_name::LookupResult::operator=(const ::fuchsia_net_name::LookupResult& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_net_name::LookupResult::operator==(const LookupResult& other) const noexcept {
  return ::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::LookupResult>::Equal(this, &other);
}
bool fuchsia_net_name::LookupResult::operator!=(const LookupResult& other) const noexcept {
  return !::fidl::internal::NaturalTableCodingTraits<::fuchsia_net_name::LookupResult>::Equal(this, &other);
}

::fuchsia_net_name::LookupResult::Storage_ fuchsia_net_name::LookupResult::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.addresses),
      ::fidl::internal::NaturalClone(storage_.canonical_name)};
}

bool fuchsia_net_name::LookupResult::IsEmpty() const {
  return !(storage_.addresses.has_value() || storage_.canonical_name.has_value());
}
const std::optional<::std::vector<::fuchsia_net::IpAddress>>& fuchsia_net_name::LookupResult::addresses() const {
  return storage_.addresses;
}

::std::optional<::std::vector<::fuchsia_net::IpAddress>>& fuchsia_net_name::LookupResult::addresses() {
  return storage_.addresses;
}

::fuchsia_net_name::LookupResult& fuchsia_net_name::LookupResult::addresses(std::optional<::std::vector<::fuchsia_net::IpAddress>> value) {
  storage_.addresses = std::move(value);
  return *this;
}
const std::optional<::std::string>& fuchsia_net_name::LookupResult::canonical_name() const {
  return storage_.canonical_name;
}

::std::optional<::std::string>& fuchsia_net_name::LookupResult::canonical_name() {
  return storage_.canonical_name;
}

::fuchsia_net_name::LookupResult& fuchsia_net_name::LookupResult::canonical_name(std::optional<::std::string> value) {
  storage_.canonical_name = std::move(value);
  return *this;
}

::fuchsia_net_name::DnsServerSource::DnsServerSource(DnsServerSource&& other) noexcept : DnsServerSource(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag{}) {
  *storage_ = std::move(*other.storage_);
}

::fuchsia_net_name::DnsServerSource& ::fuchsia_net_name::DnsServerSource::operator=(DnsServerSource&& other) noexcept {
  if (this != &other) {
    *storage_ = std::move(*other.storage_);
  }
  return *this;
}

::fuchsia_net_name::DnsServerSource::DnsServerSource(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag)
    : storage_(std::make_shared<Storage_>()) {}

::fuchsia_net_name::DnsServerSource::DnsServerSource(std::shared_ptr<Storage_> storage) : storage_(std::move(storage)) {}

::fuchsia_net_name::DnsServerSource::Tag fuchsia_net_name::DnsServerSource::Which() const {
  return DnsServerSource::IndexToTag(storage_->index()).value();
}

size_t fuchsia_net_name::DnsServerSource::TagToIndex(::fidl::internal::NaturalDecoder* decoder, ::fuchsia_net_name::DnsServerSource::Tag tag) {
  switch (tag) {
    case ::fuchsia_net_name::DnsServerSource::Tag::kStaticSource:
      return 1;
    case ::fuchsia_net_name::DnsServerSource::Tag::kDhcp:
      return 2;
    case ::fuchsia_net_name::DnsServerSource::Tag::kNdp:
      return 3;
    case ::fuchsia_net_name::DnsServerSource::Tag::kDhcpv6:
      return 4;
    case ::fuchsia_net_name::DnsServerSource::Tag::kSocketProxy:
      return 5;
    default: {
      return 0;
    }
  }
}

std::optional<::fuchsia_net_name::DnsServerSource::Tag> fuchsia_net_name::DnsServerSource::IndexToTag(size_t index) {
  switch (index) {
    case 1:
      return ::fuchsia_net_name::DnsServerSource::Tag::kStaticSource;
    case 2:
      return ::fuchsia_net_name::DnsServerSource::Tag::kDhcp;
    case 3:
      return ::fuchsia_net_name::DnsServerSource::Tag::kNdp;
    case 4:
      return ::fuchsia_net_name::DnsServerSource::Tag::kDhcpv6;
    case 5:
      return ::fuchsia_net_name::DnsServerSource::Tag::kSocketProxy;
    default:
      return ::fuchsia_net_name::DnsServerSource::Tag::_do_not_handle_this__write_a_default_case_instead;
  }
}

::fuchsia_net_name::DnsServerSource::DnsServerSource(const DnsServerSource& other) noexcept : DnsServerSource(other.CloneStorage_()) {}

::fuchsia_net_name::DnsServerSource& fuchsia_net_name::DnsServerSource::operator=(const DnsServerSource& other) noexcept {
  if (this != &other) {
    storage_ = other.CloneStorage_();
  }
  return *this;
}

bool fuchsia_net_name::DnsServerSource::operator==(const DnsServerSource& other) const noexcept {
  return *storage_ == *other.storage_;
}
bool fuchsia_net_name::DnsServerSource::operator!=(const DnsServerSource& other) const noexcept {
  return *storage_ != *other.storage_;
}

std::shared_ptr<::fuchsia_net_name::DnsServerSource::Storage_> fuchsia_net_name::DnsServerSource::CloneStorage_() const {
  const Storage_& storage = *storage_;
  switch (storage_->index()) {
    case 1:
      return std::make_shared<Storage_>(
          std::in_place_index<1>,
          ::fidl::internal::NaturalClone(std::get<1>(storage)));
    case 2:
      return std::make_shared<Storage_>(
          std::in_place_index<2>,
          ::fidl::internal::NaturalClone(std::get<2>(storage)));
    case 3:
      return std::make_shared<Storage_>(
          std::in_place_index<3>,
          ::fidl::internal::NaturalClone(std::get<3>(storage)));
    case 4:
      return std::make_shared<Storage_>(
          std::in_place_index<4>,
          ::fidl::internal::NaturalClone(std::get<4>(storage)));
    case 5:
      return std::make_shared<Storage_>(
          std::in_place_index<5>,
          ::fidl::internal::NaturalClone(std::get<5>(storage)));
    default:
      return std::make_shared<Storage_>();
  }
}
bool fuchsia_net_name::DnsServerSource::IsUnknown() const {
  return Which() == ::fuchsia_net_name::DnsServerSource::Tag::_do_not_handle_this__write_a_default_case_instead;
}
::fuchsia_net_name::DnsServerSource fuchsia_net_name::DnsServerSource::WithStaticSource(::fuchsia_net_name::StaticDnsServerSource val) {
  return DnsServerSource(std::make_shared<Storage_>(
      std::in_place_index_t<1>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<1, ::fuchsia_net_name::DnsServerSource::Storage_> fuchsia_net_name::DnsServerSource::static_source() const {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<1, ::fuchsia_net_name::DnsServerSource::Storage_> fuchsia_net_name::DnsServerSource::static_source() {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fuchsia_net_name::DnsServerSource& fuchsia_net_name::DnsServerSource::static_source(::fuchsia_net_name::StaticDnsServerSource value) {
  storage_->emplace<1>(std::move(value));
  return *this;
}
::fuchsia_net_name::DnsServerSource fuchsia_net_name::DnsServerSource::WithDhcp(::fuchsia_net_name::DhcpDnsServerSource val) {
  return DnsServerSource(std::make_shared<Storage_>(
      std::in_place_index_t<2>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<2, ::fuchsia_net_name::DnsServerSource::Storage_> fuchsia_net_name::DnsServerSource::dhcp() const {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<2, ::fuchsia_net_name::DnsServerSource::Storage_> fuchsia_net_name::DnsServerSource::dhcp() {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fuchsia_net_name::DnsServerSource& fuchsia_net_name::DnsServerSource::dhcp(::fuchsia_net_name::DhcpDnsServerSource value) {
  storage_->emplace<2>(std::move(value));
  return *this;
}
::fuchsia_net_name::DnsServerSource fuchsia_net_name::DnsServerSource::WithNdp(::fuchsia_net_name::NdpDnsServerSource val) {
  return DnsServerSource(std::make_shared<Storage_>(
      std::in_place_index_t<3>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<3, ::fuchsia_net_name::DnsServerSource::Storage_> fuchsia_net_name::DnsServerSource::ndp() const {
  return ::fidl::internal::UnionMemberView<3, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<3, ::fuchsia_net_name::DnsServerSource::Storage_> fuchsia_net_name::DnsServerSource::ndp() {
  return ::fidl::internal::UnionMemberView<3, Storage_>(storage_);
}

::fuchsia_net_name::DnsServerSource& fuchsia_net_name::DnsServerSource::ndp(::fuchsia_net_name::NdpDnsServerSource value) {
  storage_->emplace<3>(std::move(value));
  return *this;
}
::fuchsia_net_name::DnsServerSource fuchsia_net_name::DnsServerSource::WithDhcpv6(::fuchsia_net_name::Dhcpv6DnsServerSource val) {
  return DnsServerSource(std::make_shared<Storage_>(
      std::in_place_index_t<4>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<4, ::fuchsia_net_name::DnsServerSource::Storage_> fuchsia_net_name::DnsServerSource::dhcpv6() const {
  return ::fidl::internal::UnionMemberView<4, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<4, ::fuchsia_net_name::DnsServerSource::Storage_> fuchsia_net_name::DnsServerSource::dhcpv6() {
  return ::fidl::internal::UnionMemberView<4, Storage_>(storage_);
}

::fuchsia_net_name::DnsServerSource& fuchsia_net_name::DnsServerSource::dhcpv6(::fuchsia_net_name::Dhcpv6DnsServerSource value) {
  storage_->emplace<4>(std::move(value));
  return *this;
}
::fuchsia_net_name::DnsServerSource fuchsia_net_name::DnsServerSource::WithSocketProxy(::fuchsia_net_name::SocketProxyDnsServerSource val) {
  return DnsServerSource(std::make_shared<Storage_>(
      std::in_place_index_t<5>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<5, ::fuchsia_net_name::DnsServerSource::Storage_> fuchsia_net_name::DnsServerSource::socket_proxy() const {
  return ::fidl::internal::UnionMemberView<5, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<5, ::fuchsia_net_name::DnsServerSource::Storage_> fuchsia_net_name::DnsServerSource::socket_proxy() {
  return ::fidl::internal::UnionMemberView<5, Storage_>(storage_);
}

::fuchsia_net_name::DnsServerSource& fuchsia_net_name::DnsServerSource::socket_proxy(::fuchsia_net_name::SocketProxyDnsServerSource value) {
  storage_->emplace<5>(std::move(value));
  return *this;
}

::fuchsia_net_name::LookupLookupIpResult::LookupLookupIpResult(LookupLookupIpResult&& other) noexcept : LookupLookupIpResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag{}) {
  *storage_ = std::move(*other.storage_);
}

::fuchsia_net_name::LookupLookupIpResult& ::fuchsia_net_name::LookupLookupIpResult::operator=(LookupLookupIpResult&& other) noexcept {
  if (this != &other) {
    *storage_ = std::move(*other.storage_);
  }
  return *this;
}

::fuchsia_net_name::LookupLookupIpResult::LookupLookupIpResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag)
    : storage_(std::make_shared<Storage_>()) {}

::fuchsia_net_name::LookupLookupIpResult::LookupLookupIpResult(std::shared_ptr<Storage_> storage) : storage_(std::move(storage)) {}

::fuchsia_net_name::LookupLookupIpResult::Tag fuchsia_net_name::LookupLookupIpResult::Which() const {
  return LookupLookupIpResult::IndexToTag(storage_->index()).value();
}

size_t fuchsia_net_name::LookupLookupIpResult::TagToIndex(::fidl::internal::NaturalDecoder* decoder, ::fuchsia_net_name::LookupLookupIpResult::Tag tag) {
  switch (tag) {
    case ::fuchsia_net_name::LookupLookupIpResult::Tag::kResponse:
      return 1;
    case ::fuchsia_net_name::LookupLookupIpResult::Tag::kErr:
      return 2;
    default: {
      decoder->SetError(::fidl::internal::kCodingErrorUnknownUnionTag);
      return 0;
    }
  }
}

std::optional<::fuchsia_net_name::LookupLookupIpResult::Tag> fuchsia_net_name::LookupLookupIpResult::IndexToTag(size_t index) {
  switch (index) {
    case 1:
      return ::fuchsia_net_name::LookupLookupIpResult::Tag::kResponse;
    case 2:
      return ::fuchsia_net_name::LookupLookupIpResult::Tag::kErr;
    default:
      return std::nullopt;
  }
}

::fuchsia_net_name::LookupLookupIpResult::LookupLookupIpResult(const LookupLookupIpResult& other) noexcept : LookupLookupIpResult(other.CloneStorage_()) {}

::fuchsia_net_name::LookupLookupIpResult& fuchsia_net_name::LookupLookupIpResult::operator=(const LookupLookupIpResult& other) noexcept {
  if (this != &other) {
    storage_ = other.CloneStorage_();
  }
  return *this;
}

bool fuchsia_net_name::LookupLookupIpResult::operator==(const LookupLookupIpResult& other) const noexcept {
  return *storage_ == *other.storage_;
}
bool fuchsia_net_name::LookupLookupIpResult::operator!=(const LookupLookupIpResult& other) const noexcept {
  return *storage_ != *other.storage_;
}

std::shared_ptr<::fuchsia_net_name::LookupLookupIpResult::Storage_> fuchsia_net_name::LookupLookupIpResult::CloneStorage_() const {
  const Storage_& storage = *storage_;
  switch (storage_->index()) {
    case 1:
      return std::make_shared<Storage_>(
          std::in_place_index<1>,
          ::fidl::internal::NaturalClone(std::get<1>(storage)));
    case 2:
      return std::make_shared<Storage_>(
          std::in_place_index<2>,
          ::fidl::internal::NaturalClone(std::get<2>(storage)));
    default:
      return std::make_shared<Storage_>();
  }
}
::fuchsia_net_name::LookupLookupIpResult fuchsia_net_name::LookupLookupIpResult::WithResponse(::fuchsia_net_name::LookupLookupIpResponse val) {
  return LookupLookupIpResult(std::make_shared<Storage_>(
      std::in_place_index_t<1>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<1, ::fuchsia_net_name::LookupLookupIpResult::Storage_> fuchsia_net_name::LookupLookupIpResult::response() const {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<1, ::fuchsia_net_name::LookupLookupIpResult::Storage_> fuchsia_net_name::LookupLookupIpResult::response() {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fuchsia_net_name::LookupLookupIpResult& fuchsia_net_name::LookupLookupIpResult::response(::fuchsia_net_name::LookupLookupIpResponse value) {
  storage_->emplace<1>(std::move(value));
  return *this;
}
::fuchsia_net_name::LookupLookupIpResult fuchsia_net_name::LookupLookupIpResult::WithErr(::fuchsia_net_name::LookupError val) {
  return LookupLookupIpResult(std::make_shared<Storage_>(
      std::in_place_index_t<2>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<2, ::fuchsia_net_name::LookupLookupIpResult::Storage_> fuchsia_net_name::LookupLookupIpResult::err() const {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<2, ::fuchsia_net_name::LookupLookupIpResult::Storage_> fuchsia_net_name::LookupLookupIpResult::err() {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fuchsia_net_name::LookupLookupIpResult& fuchsia_net_name::LookupLookupIpResult::err(::fuchsia_net_name::LookupError value) {
  storage_->emplace<2>(std::move(value));
  return *this;
}

::fuchsia_net_name::LookupLookupHostnameResult::LookupLookupHostnameResult(LookupLookupHostnameResult&& other) noexcept : LookupLookupHostnameResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag{}) {
  *storage_ = std::move(*other.storage_);
}

::fuchsia_net_name::LookupLookupHostnameResult& ::fuchsia_net_name::LookupLookupHostnameResult::operator=(LookupLookupHostnameResult&& other) noexcept {
  if (this != &other) {
    *storage_ = std::move(*other.storage_);
  }
  return *this;
}

::fuchsia_net_name::LookupLookupHostnameResult::LookupLookupHostnameResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag)
    : storage_(std::make_shared<Storage_>()) {}

::fuchsia_net_name::LookupLookupHostnameResult::LookupLookupHostnameResult(std::shared_ptr<Storage_> storage) : storage_(std::move(storage)) {}

::fuchsia_net_name::LookupLookupHostnameResult::Tag fuchsia_net_name::LookupLookupHostnameResult::Which() const {
  return LookupLookupHostnameResult::IndexToTag(storage_->index()).value();
}

size_t fuchsia_net_name::LookupLookupHostnameResult::TagToIndex(::fidl::internal::NaturalDecoder* decoder, ::fuchsia_net_name::LookupLookupHostnameResult::Tag tag) {
  switch (tag) {
    case ::fuchsia_net_name::LookupLookupHostnameResult::Tag::kResponse:
      return 1;
    case ::fuchsia_net_name::LookupLookupHostnameResult::Tag::kErr:
      return 2;
    default: {
      decoder->SetError(::fidl::internal::kCodingErrorUnknownUnionTag);
      return 0;
    }
  }
}

std::optional<::fuchsia_net_name::LookupLookupHostnameResult::Tag> fuchsia_net_name::LookupLookupHostnameResult::IndexToTag(size_t index) {
  switch (index) {
    case 1:
      return ::fuchsia_net_name::LookupLookupHostnameResult::Tag::kResponse;
    case 2:
      return ::fuchsia_net_name::LookupLookupHostnameResult::Tag::kErr;
    default:
      return std::nullopt;
  }
}

::fuchsia_net_name::LookupLookupHostnameResult::LookupLookupHostnameResult(const LookupLookupHostnameResult& other) noexcept : LookupLookupHostnameResult(other.CloneStorage_()) {}

::fuchsia_net_name::LookupLookupHostnameResult& fuchsia_net_name::LookupLookupHostnameResult::operator=(const LookupLookupHostnameResult& other) noexcept {
  if (this != &other) {
    storage_ = other.CloneStorage_();
  }
  return *this;
}

bool fuchsia_net_name::LookupLookupHostnameResult::operator==(const LookupLookupHostnameResult& other) const noexcept {
  return *storage_ == *other.storage_;
}
bool fuchsia_net_name::LookupLookupHostnameResult::operator!=(const LookupLookupHostnameResult& other) const noexcept {
  return *storage_ != *other.storage_;
}

std::shared_ptr<::fuchsia_net_name::LookupLookupHostnameResult::Storage_> fuchsia_net_name::LookupLookupHostnameResult::CloneStorage_() const {
  const Storage_& storage = *storage_;
  switch (storage_->index()) {
    case 1:
      return std::make_shared<Storage_>(
          std::in_place_index<1>,
          ::fidl::internal::NaturalClone(std::get<1>(storage)));
    case 2:
      return std::make_shared<Storage_>(
          std::in_place_index<2>,
          ::fidl::internal::NaturalClone(std::get<2>(storage)));
    default:
      return std::make_shared<Storage_>();
  }
}
::fuchsia_net_name::LookupLookupHostnameResult fuchsia_net_name::LookupLookupHostnameResult::WithResponse(::fuchsia_net_name::LookupLookupHostnameResponse val) {
  return LookupLookupHostnameResult(std::make_shared<Storage_>(
      std::in_place_index_t<1>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<1, ::fuchsia_net_name::LookupLookupHostnameResult::Storage_> fuchsia_net_name::LookupLookupHostnameResult::response() const {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<1, ::fuchsia_net_name::LookupLookupHostnameResult::Storage_> fuchsia_net_name::LookupLookupHostnameResult::response() {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fuchsia_net_name::LookupLookupHostnameResult& fuchsia_net_name::LookupLookupHostnameResult::response(::fuchsia_net_name::LookupLookupHostnameResponse value) {
  storage_->emplace<1>(std::move(value));
  return *this;
}
::fuchsia_net_name::LookupLookupHostnameResult fuchsia_net_name::LookupLookupHostnameResult::WithErr(::fuchsia_net_name::LookupError val) {
  return LookupLookupHostnameResult(std::make_shared<Storage_>(
      std::in_place_index_t<2>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<2, ::fuchsia_net_name::LookupLookupHostnameResult::Storage_> fuchsia_net_name::LookupLookupHostnameResult::err() const {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<2, ::fuchsia_net_name::LookupLookupHostnameResult::Storage_> fuchsia_net_name::LookupLookupHostnameResult::err() {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fuchsia_net_name::LookupLookupHostnameResult& fuchsia_net_name::LookupLookupHostnameResult::err(::fuchsia_net_name::LookupError value) {
  storage_->emplace<2>(std::move(value));
  return *this;
}

::fuchsia_net_name::LookupAdminSetDnsServersResult::LookupAdminSetDnsServersResult(LookupAdminSetDnsServersResult&& other) noexcept : LookupAdminSetDnsServersResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag{}) {
  *storage_ = std::move(*other.storage_);
}

::fuchsia_net_name::LookupAdminSetDnsServersResult& ::fuchsia_net_name::LookupAdminSetDnsServersResult::operator=(LookupAdminSetDnsServersResult&& other) noexcept {
  if (this != &other) {
    *storage_ = std::move(*other.storage_);
  }
  return *this;
}

::fuchsia_net_name::LookupAdminSetDnsServersResult::LookupAdminSetDnsServersResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag)
    : storage_(std::make_shared<Storage_>()) {}

::fuchsia_net_name::LookupAdminSetDnsServersResult::LookupAdminSetDnsServersResult(std::shared_ptr<Storage_> storage) : storage_(std::move(storage)) {}

::fuchsia_net_name::LookupAdminSetDnsServersResult::Tag fuchsia_net_name::LookupAdminSetDnsServersResult::Which() const {
  return LookupAdminSetDnsServersResult::IndexToTag(storage_->index()).value();
}

size_t fuchsia_net_name::LookupAdminSetDnsServersResult::TagToIndex(::fidl::internal::NaturalDecoder* decoder, ::fuchsia_net_name::LookupAdminSetDnsServersResult::Tag tag) {
  switch (tag) {
    case ::fuchsia_net_name::LookupAdminSetDnsServersResult::Tag::kResponse:
      return 1;
    case ::fuchsia_net_name::LookupAdminSetDnsServersResult::Tag::kErr:
      return 2;
    default: {
      decoder->SetError(::fidl::internal::kCodingErrorUnknownUnionTag);
      return 0;
    }
  }
}

std::optional<::fuchsia_net_name::LookupAdminSetDnsServersResult::Tag> fuchsia_net_name::LookupAdminSetDnsServersResult::IndexToTag(size_t index) {
  switch (index) {
    case 1:
      return ::fuchsia_net_name::LookupAdminSetDnsServersResult::Tag::kResponse;
    case 2:
      return ::fuchsia_net_name::LookupAdminSetDnsServersResult::Tag::kErr;
    default:
      return std::nullopt;
  }
}

::fuchsia_net_name::LookupAdminSetDnsServersResult::LookupAdminSetDnsServersResult(const LookupAdminSetDnsServersResult& other) noexcept : LookupAdminSetDnsServersResult(other.CloneStorage_()) {}

::fuchsia_net_name::LookupAdminSetDnsServersResult& fuchsia_net_name::LookupAdminSetDnsServersResult::operator=(const LookupAdminSetDnsServersResult& other) noexcept {
  if (this != &other) {
    storage_ = other.CloneStorage_();
  }
  return *this;
}

bool fuchsia_net_name::LookupAdminSetDnsServersResult::operator==(const LookupAdminSetDnsServersResult& other) const noexcept {
  return *storage_ == *other.storage_;
}
bool fuchsia_net_name::LookupAdminSetDnsServersResult::operator!=(const LookupAdminSetDnsServersResult& other) const noexcept {
  return *storage_ != *other.storage_;
}

std::shared_ptr<::fuchsia_net_name::LookupAdminSetDnsServersResult::Storage_> fuchsia_net_name::LookupAdminSetDnsServersResult::CloneStorage_() const {
  const Storage_& storage = *storage_;
  switch (storage_->index()) {
    case 1:
      return std::make_shared<Storage_>(
          std::in_place_index<1>,
          ::fidl::internal::NaturalClone(std::get<1>(storage)));
    case 2:
      return std::make_shared<Storage_>(
          std::in_place_index<2>,
          ::fidl::internal::NaturalClone(std::get<2>(storage)));
    default:
      return std::make_shared<Storage_>();
  }
}
::fuchsia_net_name::LookupAdminSetDnsServersResult fuchsia_net_name::LookupAdminSetDnsServersResult::WithResponse(::fuchsia_net_name::LookupAdminSetDnsServersResponse val) {
  return LookupAdminSetDnsServersResult(std::make_shared<Storage_>(
      std::in_place_index_t<1>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<1, ::fuchsia_net_name::LookupAdminSetDnsServersResult::Storage_> fuchsia_net_name::LookupAdminSetDnsServersResult::response() const {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<1, ::fuchsia_net_name::LookupAdminSetDnsServersResult::Storage_> fuchsia_net_name::LookupAdminSetDnsServersResult::response() {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fuchsia_net_name::LookupAdminSetDnsServersResult& fuchsia_net_name::LookupAdminSetDnsServersResult::response(::fuchsia_net_name::LookupAdminSetDnsServersResponse value) {
  storage_->emplace<1>(std::move(value));
  return *this;
}
::fuchsia_net_name::LookupAdminSetDnsServersResult fuchsia_net_name::LookupAdminSetDnsServersResult::WithErr(int32_t val) {
  return LookupAdminSetDnsServersResult(std::make_shared<Storage_>(
      std::in_place_index_t<2>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<2, ::fuchsia_net_name::LookupAdminSetDnsServersResult::Storage_> fuchsia_net_name::LookupAdminSetDnsServersResult::err() const {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<2, ::fuchsia_net_name::LookupAdminSetDnsServersResult::Storage_> fuchsia_net_name::LookupAdminSetDnsServersResult::err() {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fuchsia_net_name::LookupAdminSetDnsServersResult& fuchsia_net_name::LookupAdminSetDnsServersResult::err(int32_t value) {
  storage_->emplace<2>(std::move(value));
  return *this;
}

#pragma clang diagnostic pop
