// WARNING: This file is machine generated by fidlgen.

#include <fidl/fuchsia.virtualconsole/cpp/natural_ostream.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wshadow"

#if __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fuchsia_virtualconsole::SessionManagerCreateSessionRequest>::Format(std::ostream& os, const ::fuchsia_virtualconsole::SessionManagerCreateSessionRequest& value) {
  os << "fuchsia_virtualconsole::SessionManagerCreateSessionRequest";
  os << "{ ";
  os << "session";
  os << " = " << fidl::ostream::Formatted<::fidl::ServerEnd<::fuchsia_hardware_pty::Device>>(value.session()) << ", ";
  os << "}";
  return os;
}

#endif  // __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fuchsia_virtualconsole::SessionManagerHasPrimaryConnectedResponse>::Format(std::ostream& os, const ::fuchsia_virtualconsole::SessionManagerHasPrimaryConnectedResponse& value) {
  os << "fuchsia_virtualconsole::SessionManagerHasPrimaryConnectedResponse";
  os << "{ ";
  os << "connected";
  os << " = " << fidl::ostream::Formatted<bool>(value.connected()) << ", ";
  os << "}";
  return os;
}
#if __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fidl::ClientEnd<::fuchsia_virtualconsole::SessionManager>>::Format(std::ostream& os, const ::fidl::ClientEnd<::fuchsia_virtualconsole::SessionManager>& value) {
  return os << "ClientEnd<" << "fuchsia_virtualconsole::SessionManager" << ">(" << value.channel().get() << ")";
}

std::ostream& fidl::ostream::Formatter<::fidl::ServerEnd<::fuchsia_virtualconsole::SessionManager>>::Format(std::ostream& os, const ::fidl::ServerEnd<::fuchsia_virtualconsole::SessionManager>& value) {
  return os << "ServerEnd<" << "fuchsia_virtualconsole::SessionManager" << ">(" << value.channel().get() << ")";
}

std::ostream& operator<<(std::ostream& os, const ::fidl::ClientEnd<::fuchsia_virtualconsole::SessionManager>& value) {
  return fidl::ostream::Formatter<::fidl::ClientEnd<::fuchsia_virtualconsole::SessionManager>>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fidl::ServerEnd<::fuchsia_virtualconsole::SessionManager>& value) {
  return fidl::ostream::Formatter<::fidl::ServerEnd<::fuchsia_virtualconsole::SessionManager>>::Format(os, value);
}

#endif  // __FIDL_SUPPORT_HANDLES
namespace fuchsia_virtualconsole {

#if __FIDL_SUPPORT_HANDLES

std::ostream& operator<<(std::ostream& os, const ::fuchsia_virtualconsole::SessionManagerCreateSessionRequest& value) {
  return fidl::ostream::Formatter<::fuchsia_virtualconsole::SessionManagerCreateSessionRequest>::Format(os, value);
}

#endif  // __FIDL_SUPPORT_HANDLES

std::ostream& operator<<(std::ostream& os, const ::fuchsia_virtualconsole::SessionManagerHasPrimaryConnectedResponse& value) {
  return fidl::ostream::Formatter<::fuchsia_virtualconsole::SessionManagerHasPrimaryConnectedResponse>::Format(os, value);
}

#pragma clang diagnostic pop

}  // namespace fuchsia_virtualconsole
