// WARNING: This file is machine generated by fidlgen.

#include <fidl/fuchsia.hardware.inlineencryption/cpp/natural_ostream.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wshadow"

#if __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fuchsia_hardware_inlineencryption::DeviceProgramKeyRequest>::Format(std::ostream& os, const ::fuchsia_hardware_inlineencryption::DeviceProgramKeyRequest& value) {
  os << "fuchsia_hardware_inlineencryption::DeviceProgramKeyRequest";
  os << "{ ";
  os << "wrapped_key";
  os << " = " << fidl::ostream::Formatted<::std::vector<uint8_t>>(value.wrapped_key()) << ", ";
  os << "data_unit_size";
  os << " = " << fidl::ostream::Formatted<uint32_t>(value.data_unit_size()) << ", ";
  os << "}";
  return os;
}

#endif  // __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fuchsia_hardware_inlineencryption::DeviceProgramKeyResponse>::Format(std::ostream& os, const ::fuchsia_hardware_inlineencryption::DeviceProgramKeyResponse& value) {
  os << "fuchsia_hardware_inlineencryption::DeviceProgramKeyResponse";
  os << "{ ";
  os << "slot";
  os << " = " << fidl::ostream::Formatted<uint8_t>(value.slot()) << ", ";
  os << "}";
  return os;
}
#if __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretRequest>::Format(std::ostream& os, const ::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretRequest& value) {
  os << "fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretRequest";
  os << "{ ";
  os << "wrapped_key";
  os << " = " << fidl::ostream::Formatted<::std::vector<uint8_t>>(value.wrapped_key()) << ", ";
  os << "}";
  return os;
}

std::ostream& fidl::ostream::Formatter<::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResponse>::Format(std::ostream& os, const ::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResponse& value) {
  os << "fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResponse";
  os << "{ ";
  os << "secret";
  os << " = " << fidl::ostream::Formatted<::std::vector<uint8_t>>(value.secret()) << ", ";
  os << "}";
  return os;
}

#endif  // __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fuchsia_hardware_inlineencryption::DeviceProgramKeyResult>::Format(std::ostream& os, const ::fuchsia_hardware_inlineencryption::DeviceProgramKeyResult& value) {
  os << "fuchsia_hardware_inlineencryption::DeviceProgramKeyResult::";
  switch (value.Which()) {
    case ::fuchsia_hardware_inlineencryption::DeviceProgramKeyResult::Tag::kResponse:
      os << "response(" << fidl::ostream::Formatted<::fuchsia_hardware_inlineencryption::DeviceProgramKeyResponse>(value.response().value()) << ")";
      break;
    case ::fuchsia_hardware_inlineencryption::DeviceProgramKeyResult::Tag::kErr:
      os << "err(" << fidl::ostream::Formatted<int32_t>(value.err().value()) << ")";
      break;
    default:
      os << "Unknown";
  }
  return os;
}
#if __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResult>::Format(std::ostream& os, const ::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResult& value) {
  os << "fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResult::";
  switch (value.Which()) {
    case ::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResult::Tag::kResponse:
      os << "response(" << fidl::ostream::Formatted<::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResponse>(value.response().value()) << ")";
      break;
    case ::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResult::Tag::kErr:
      os << "err(" << fidl::ostream::Formatted<int32_t>(value.err().value()) << ")";
      break;
    default:
      os << "Unknown";
  }
  return os;
}

std::ostream& fidl::ostream::Formatter<::fidl::ClientEnd<::fuchsia_hardware_inlineencryption::Device>>::Format(std::ostream& os, const ::fidl::ClientEnd<::fuchsia_hardware_inlineencryption::Device>& value) {
  return os << "ClientEnd<" << "fuchsia_hardware_inlineencryption::Device" << ">(" << value.channel().get() << ")";
}

std::ostream& fidl::ostream::Formatter<::fidl::ServerEnd<::fuchsia_hardware_inlineencryption::Device>>::Format(std::ostream& os, const ::fidl::ServerEnd<::fuchsia_hardware_inlineencryption::Device>& value) {
  return os << "ServerEnd<" << "fuchsia_hardware_inlineencryption::Device" << ">(" << value.channel().get() << ")";
}

std::ostream& operator<<(std::ostream& os, const ::fidl::ClientEnd<::fuchsia_hardware_inlineencryption::Device>& value) {
  return fidl::ostream::Formatter<::fidl::ClientEnd<::fuchsia_hardware_inlineencryption::Device>>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fidl::ServerEnd<::fuchsia_hardware_inlineencryption::Device>& value) {
  return fidl::ostream::Formatter<::fidl::ServerEnd<::fuchsia_hardware_inlineencryption::Device>>::Format(os, value);
}
std::ostream& fidl::ostream::Formatter<::fdf::ClientEnd<::fuchsia_hardware_inlineencryption::DriverDevice>>::Format(std::ostream& os, const ::fdf::ClientEnd<::fuchsia_hardware_inlineencryption::DriverDevice>& value) {
  return os << "ClientEnd<" << "fuchsia_hardware_inlineencryption::DriverDevice" << ">(" << value.channel().get() << ")";
}

std::ostream& fidl::ostream::Formatter<::fdf::ServerEnd<::fuchsia_hardware_inlineencryption::DriverDevice>>::Format(std::ostream& os, const ::fdf::ServerEnd<::fuchsia_hardware_inlineencryption::DriverDevice>& value) {
  return os << "ServerEnd<" << "fuchsia_hardware_inlineencryption::DriverDevice" << ">(" << value.channel().get() << ")";
}

std::ostream& operator<<(std::ostream& os, const ::fdf::ClientEnd<::fuchsia_hardware_inlineencryption::DriverDevice>& value) {
  return fidl::ostream::Formatter<::fdf::ClientEnd<::fuchsia_hardware_inlineencryption::DriverDevice>>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fdf::ServerEnd<::fuchsia_hardware_inlineencryption::DriverDevice>& value) {
  return fidl::ostream::Formatter<::fdf::ServerEnd<::fuchsia_hardware_inlineencryption::DriverDevice>>::Format(os, value);
}

#endif  // __FIDL_SUPPORT_HANDLES
namespace fuchsia_hardware_inlineencryption {

#if __FIDL_SUPPORT_HANDLES

std::ostream& operator<<(std::ostream& os, const ::fuchsia_hardware_inlineencryption::DeviceProgramKeyRequest& value) {
  return fidl::ostream::Formatter<::fuchsia_hardware_inlineencryption::DeviceProgramKeyRequest>::Format(os, value);
}

#endif  // __FIDL_SUPPORT_HANDLES

std::ostream& operator<<(std::ostream& os, const ::fuchsia_hardware_inlineencryption::DeviceProgramKeyResponse& value) {
  return fidl::ostream::Formatter<::fuchsia_hardware_inlineencryption::DeviceProgramKeyResponse>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_hardware_inlineencryption::DeviceProgramKeyResult& value) {
  return fidl::ostream::Formatter<::fuchsia_hardware_inlineencryption::DeviceProgramKeyResult>::Format(os, value);
}

#if __FIDL_SUPPORT_HANDLES

std::ostream& operator<<(std::ostream& os, const ::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretRequest& value) {
  return fidl::ostream::Formatter<::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretRequest>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResponse& value) {
  return fidl::ostream::Formatter<::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResponse>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResult& value) {
  return fidl::ostream::Formatter<::fuchsia_hardware_inlineencryption::DeviceDeriveRawSecretResult>::Format(os, value);
}

#endif  // __FIDL_SUPPORT_HANDLES

#pragma clang diagnostic pop

}  // namespace fuchsia_hardware_inlineencryption
