// WARNING: This file is machine generated by fidlgen.

#include <fidl/fuchsia.hardware.fastboot/cpp/natural_ostream.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wshadow"

#if __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fuchsia_hardware_fastboot::FastbootImplSendRequest>::Format(std::ostream& os, const ::fuchsia_hardware_fastboot::FastbootImplSendRequest& value) {
  os << "fuchsia_hardware_fastboot::FastbootImplSendRequest";
  os << "{ ";
  os << "data";
  os << " = " << fidl::ostream::Formatted<::zx::vmo>(value.data()) << ", ";
  os << "}";
  return os;
}

#endif  // __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fuchsia_hardware_fastboot::FastbootImplSendResponse>::Format(std::ostream& os, const ::fuchsia_hardware_fastboot::FastbootImplSendResponse& value) {
  os << "fuchsia_hardware_fastboot::FastbootImplSendResponse";
  os << "{ ";
  os << "__reserved";
  os << " = " << fidl::ostream::Formatted<uint8_t>(value.__reserved()) << ", ";
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_hardware_fastboot::FastbootImplReceiveRequest>::Format(std::ostream& os, const ::fuchsia_hardware_fastboot::FastbootImplReceiveRequest& value) {
  os << "fuchsia_hardware_fastboot::FastbootImplReceiveRequest";
  os << "{ ";
  os << "requested";
  os << " = " << fidl::ostream::Formatted<uint64_t>(value.requested()) << ", ";
  os << "}";
  return os;
}
#if __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fuchsia_hardware_fastboot::FastbootImplReceiveResponse>::Format(std::ostream& os, const ::fuchsia_hardware_fastboot::FastbootImplReceiveResponse& value) {
  os << "fuchsia_hardware_fastboot::FastbootImplReceiveResponse";
  os << "{ ";
  os << "data";
  os << " = " << fidl::ostream::Formatted<::zx::vmo>(value.data()) << ", ";
  os << "}";
  return os;
}

#endif  // __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fuchsia_hardware_fastboot::FastbootImplSendResult>::Format(std::ostream& os, const ::fuchsia_hardware_fastboot::FastbootImplSendResult& value) {
  os << "fuchsia_hardware_fastboot::FastbootImplSendResult::";
  switch (value.Which()) {
    case ::fuchsia_hardware_fastboot::FastbootImplSendResult::Tag::kResponse:
      os << "response(" << fidl::ostream::Formatted<::fuchsia_hardware_fastboot::FastbootImplSendResponse>(value.response().value()) << ")";
      break;
    case ::fuchsia_hardware_fastboot::FastbootImplSendResult::Tag::kErr:
      os << "err(" << fidl::ostream::Formatted<int32_t>(value.err().value()) << ")";
      break;
    default:
      os << "Unknown";
  }
  return os;
}
#if __FIDL_SUPPORT_HANDLES

std::ostream& fidl::ostream::Formatter<::fuchsia_hardware_fastboot::FastbootImplReceiveResult>::Format(std::ostream& os, const ::fuchsia_hardware_fastboot::FastbootImplReceiveResult& value) {
  os << "fuchsia_hardware_fastboot::FastbootImplReceiveResult::";
  switch (value.Which()) {
    case ::fuchsia_hardware_fastboot::FastbootImplReceiveResult::Tag::kResponse:
      os << "response(" << fidl::ostream::Formatted<::fuchsia_hardware_fastboot::FastbootImplReceiveResponse>(value.response().value()) << ")";
      break;
    case ::fuchsia_hardware_fastboot::FastbootImplReceiveResult::Tag::kErr:
      os << "err(" << fidl::ostream::Formatted<int32_t>(value.err().value()) << ")";
      break;
    default:
      os << "Unknown";
  }
  return os;
}

std::ostream& fidl::ostream::Formatter<::fidl::ClientEnd<::fuchsia_hardware_fastboot::FastbootImpl>>::Format(std::ostream& os, const ::fidl::ClientEnd<::fuchsia_hardware_fastboot::FastbootImpl>& value) {
  return os << "ClientEnd<" << "fuchsia_hardware_fastboot::FastbootImpl" << ">(" << value.channel().get() << ")";
}

std::ostream& fidl::ostream::Formatter<::fidl::ServerEnd<::fuchsia_hardware_fastboot::FastbootImpl>>::Format(std::ostream& os, const ::fidl::ServerEnd<::fuchsia_hardware_fastboot::FastbootImpl>& value) {
  return os << "ServerEnd<" << "fuchsia_hardware_fastboot::FastbootImpl" << ">(" << value.channel().get() << ")";
}

std::ostream& operator<<(std::ostream& os, const ::fidl::ClientEnd<::fuchsia_hardware_fastboot::FastbootImpl>& value) {
  return fidl::ostream::Formatter<::fidl::ClientEnd<::fuchsia_hardware_fastboot::FastbootImpl>>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fidl::ServerEnd<::fuchsia_hardware_fastboot::FastbootImpl>& value) {
  return fidl::ostream::Formatter<::fidl::ServerEnd<::fuchsia_hardware_fastboot::FastbootImpl>>::Format(os, value);
}

#endif  // __FIDL_SUPPORT_HANDLES
namespace fuchsia_hardware_fastboot {

#if __FIDL_SUPPORT_HANDLES

std::ostream& operator<<(std::ostream& os, const ::fuchsia_hardware_fastboot::FastbootImplSendRequest& value) {
  return fidl::ostream::Formatter<::fuchsia_hardware_fastboot::FastbootImplSendRequest>::Format(os, value);
}

#endif  // __FIDL_SUPPORT_HANDLES

std::ostream& operator<<(std::ostream& os, const ::fuchsia_hardware_fastboot::FastbootImplSendResponse& value) {
  return fidl::ostream::Formatter<::fuchsia_hardware_fastboot::FastbootImplSendResponse>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_hardware_fastboot::FastbootImplSendResult& value) {
  return fidl::ostream::Formatter<::fuchsia_hardware_fastboot::FastbootImplSendResult>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_hardware_fastboot::FastbootImplReceiveRequest& value) {
  return fidl::ostream::Formatter<::fuchsia_hardware_fastboot::FastbootImplReceiveRequest>::Format(os, value);
}

#if __FIDL_SUPPORT_HANDLES

std::ostream& operator<<(std::ostream& os, const ::fuchsia_hardware_fastboot::FastbootImplReceiveResponse& value) {
  return fidl::ostream::Formatter<::fuchsia_hardware_fastboot::FastbootImplReceiveResponse>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_hardware_fastboot::FastbootImplReceiveResult& value) {
  return fidl::ostream::Formatter<::fuchsia_hardware_fastboot::FastbootImplReceiveResult>::Format(os, value);
}

#endif  // __FIDL_SUPPORT_HANDLES

#pragma clang diagnostic pop

}  // namespace fuchsia_hardware_fastboot
