// WARNING: This file is machine generated by fidlgen.

#include <fidl/fuchsia.wlan.common/cpp/natural_ostream.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wshadow"

std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::WlanKeyType>::Format(std::ostream& os, const ::fuchsia_wlan_common::WlanKeyType& value) {
  os << "fuchsia_wlan_common::WlanKeyType";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::WlanKeyType::kPairwise:
      os << "kPairwise";
      break;
    case ::fuchsia_wlan_common::WlanKeyType::kGroup:
      os << "kGroup";
      break;
    case ::fuchsia_wlan_common::WlanKeyType::kIgtk:
      os << "kIgtk";
      break;
    case ::fuchsia_wlan_common::WlanKeyType::kPeer:
      os << "kPeer";
      break;
    default:
      os << "UNKNOWN(" << static_cast<int>(static_cast<uint8_t>(value)) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::DataPlaneType>::Format(std::ostream& os, const ::fuchsia_wlan_common::DataPlaneType& value) {
  os << "fuchsia_wlan_common::DataPlaneType";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::DataPlaneType::kEthernetDevice:
      os << "kEthernetDevice";
      break;
    case ::fuchsia_wlan_common::DataPlaneType::kGenericNetworkDevice:
      os << "kGenericNetworkDevice";
      break;
    default:
      os << "UNKNOWN(" << static_cast<int>(static_cast<uint8_t>(value)) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::MacImplementationType>::Format(std::ostream& os, const ::fuchsia_wlan_common::MacImplementationType& value) {
  os << "fuchsia_wlan_common::MacImplementationType";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::MacImplementationType::kSoftmac:
      os << "kSoftmac";
      break;
    case ::fuchsia_wlan_common::MacImplementationType::kFullmac:
      os << "kFullmac";
      break;
    default:
      os << "UNKNOWN(" << static_cast<int>(static_cast<uint8_t>(value)) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::ChannelBandwidth>::Format(std::ostream& os, const ::fuchsia_wlan_common::ChannelBandwidth& value) {
  os << "fuchsia_wlan_common::ChannelBandwidth";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::ChannelBandwidth::kCbw20:
      os << "kCbw20";
      break;
    case ::fuchsia_wlan_common::ChannelBandwidth::kCbw40:
      os << "kCbw40";
      break;
    case ::fuchsia_wlan_common::ChannelBandwidth::kCbw40Below:
      os << "kCbw40Below";
      break;
    case ::fuchsia_wlan_common::ChannelBandwidth::kCbw80:
      os << "kCbw80";
      break;
    case ::fuchsia_wlan_common::ChannelBandwidth::kCbw160:
      os << "kCbw160";
      break;
    case ::fuchsia_wlan_common::ChannelBandwidth::kCbw80P80:
      os << "kCbw80P80";
      break;
    default:
      os << "UNKNOWN(" << static_cast<uint32_t>(value) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::WlanPhyType>::Format(std::ostream& os, const ::fuchsia_wlan_common::WlanPhyType& value) {
  os << "fuchsia_wlan_common::WlanPhyType";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::WlanPhyType::kDsss:
      os << "kDsss";
      break;
    case ::fuchsia_wlan_common::WlanPhyType::kHr:
      os << "kHr";
      break;
    case ::fuchsia_wlan_common::WlanPhyType::kOfdm:
      os << "kOfdm";
      break;
    case ::fuchsia_wlan_common::WlanPhyType::kErp:
      os << "kErp";
      break;
    case ::fuchsia_wlan_common::WlanPhyType::kHt:
      os << "kHt";
      break;
    case ::fuchsia_wlan_common::WlanPhyType::kDmg:
      os << "kDmg";
      break;
    case ::fuchsia_wlan_common::WlanPhyType::kVht:
      os << "kVht";
      break;
    case ::fuchsia_wlan_common::WlanPhyType::kTvht:
      os << "kTvht";
      break;
    case ::fuchsia_wlan_common::WlanPhyType::kS1G:
      os << "kS1G";
      break;
    case ::fuchsia_wlan_common::WlanPhyType::kCdmg:
      os << "kCdmg";
      break;
    case ::fuchsia_wlan_common::WlanPhyType::kCmmg:
      os << "kCmmg";
      break;
    case ::fuchsia_wlan_common::WlanPhyType::kHe:
      os << "kHe";
      break;
    default:
      os << "UNKNOWN(" << static_cast<uint32_t>(value) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::WlanMacRole>::Format(std::ostream& os, const ::fuchsia_wlan_common::WlanMacRole& value) {
  os << "fuchsia_wlan_common::WlanMacRole";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::WlanMacRole::kClient:
      os << "kClient";
      break;
    case ::fuchsia_wlan_common::WlanMacRole::kAp:
      os << "kAp";
      break;
    case ::fuchsia_wlan_common::WlanMacRole::kMesh:
      os << "kMesh";
      break;
    default:
      os << "UNKNOWN(" << static_cast<uint32_t>(value) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::ScanType>::Format(std::ostream& os, const ::fuchsia_wlan_common::ScanType& value) {
  os << "fuchsia_wlan_common::ScanType";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::ScanType::kActive:
      os << "kActive";
      break;
    case ::fuchsia_wlan_common::ScanType::kPassive:
      os << "kPassive";
      break;
    default:
      os << "UNKNOWN(" << static_cast<uint32_t>(value) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::GuardInterval>::Format(std::ostream& os, const ::fuchsia_wlan_common::GuardInterval& value) {
  os << "fuchsia_wlan_common::GuardInterval";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::GuardInterval::kLongGi:
      os << "kLongGi";
      break;
    case ::fuchsia_wlan_common::GuardInterval::kShortGi:
      os << "kShortGi";
      break;
    default:
      os << "UNKNOWN(" << static_cast<int>(static_cast<uint8_t>(value)) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::PowerSaveType>::Format(std::ostream& os, const ::fuchsia_wlan_common::PowerSaveType& value) {
  os << "fuchsia_wlan_common::PowerSaveType";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::PowerSaveType::kPsModeUltraLowPower:
      os << "kPsModeUltraLowPower";
      break;
    case ::fuchsia_wlan_common::PowerSaveType::kPsModeLowPower:
      os << "kPsModeLowPower";
      break;
    case ::fuchsia_wlan_common::PowerSaveType::kPsModeBalanced:
      os << "kPsModeBalanced";
      break;
    case ::fuchsia_wlan_common::PowerSaveType::kPsModePerformance:
      os << "kPsModePerformance";
      break;
    default:
      os << "UNKNOWN(" << static_cast<uint32_t>(value) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::WlanTxResultCode>::Format(std::ostream& os, const ::fuchsia_wlan_common::WlanTxResultCode& value) {
  os << "fuchsia_wlan_common::WlanTxResultCode";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::WlanTxResultCode::kFailed:
      os << "kFailed";
      break;
    case ::fuchsia_wlan_common::WlanTxResultCode::kSuccess:
      os << "kSuccess";
      break;
    default:
      os << "UNKNOWN(" << static_cast<int>(static_cast<uint8_t>(value)) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::WlanSoftmacHardwareCapabilityBit>::Format(std::ostream& os, const ::fuchsia_wlan_common::WlanSoftmacHardwareCapabilityBit& value) {
  os << "fuchsia_wlan_common::WlanSoftmacHardwareCapabilityBit";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::WlanSoftmacHardwareCapabilityBit::kShortPreamble:
      os << "kShortPreamble";
      break;
    case ::fuchsia_wlan_common::WlanSoftmacHardwareCapabilityBit::kSpectrumMgmt:
      os << "kSpectrumMgmt";
      break;
    case ::fuchsia_wlan_common::WlanSoftmacHardwareCapabilityBit::kQos:
      os << "kQos";
      break;
    case ::fuchsia_wlan_common::WlanSoftmacHardwareCapabilityBit::kShortSlotTime:
      os << "kShortSlotTime";
      break;
    case ::fuchsia_wlan_common::WlanSoftmacHardwareCapabilityBit::kRadioMsmt:
      os << "kRadioMsmt";
      break;
    case ::fuchsia_wlan_common::WlanSoftmacHardwareCapabilityBit::kSimultaneousClientAp:
      os << "kSimultaneousClientAp";
      break;
    default:
      os << "UNKNOWN(" << static_cast<uint32_t>(value) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::BssType>::Format(std::ostream& os, const ::fuchsia_wlan_common::BssType& value) {
  os << "fuchsia_wlan_common::BssType";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::BssType::kUnknown:
      os << "kUnknown";
      break;
    case ::fuchsia_wlan_common::BssType::kInfrastructure:
      os << "kInfrastructure";
      break;
    case ::fuchsia_wlan_common::BssType::kIndependent:
      os << "kIndependent";
      break;
    case ::fuchsia_wlan_common::BssType::kMesh:
      os << "kMesh";
      break;
    case ::fuchsia_wlan_common::BssType::kPersonal:
      os << "kPersonal";
      break;
    default:
      os << "UNKNOWN(" << static_cast<uint32_t>(value) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::WlanProtection>::Format(std::ostream& os, const ::fuchsia_wlan_common::WlanProtection& value) {
  os << "fuchsia_wlan_common::WlanProtection";
  os << "::";
  switch (value) {
    case ::fuchsia_wlan_common::WlanProtection::kNone:
      os << "kNone";
      break;
    case ::fuchsia_wlan_common::WlanProtection::kRx:
      os << "kRx";
      break;
    case ::fuchsia_wlan_common::WlanProtection::kTx:
      os << "kTx";
      break;
    case ::fuchsia_wlan_common::WlanProtection::kRxTx:
      os << "kRxTx";
      break;
    default:
      os << "UNKNOWN(" << static_cast<int>(static_cast<uint8_t>(value)) << ")";
  }
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::WlanWmmAccessCategoryParameters>::Format(std::ostream& os, const ::fuchsia_wlan_common::WlanWmmAccessCategoryParameters& value) {
  os << "fuchsia_wlan_common::WlanWmmAccessCategoryParameters";
  os << "{ ";
  os << "ecw_min";
  os << " = " << fidl::ostream::Formatted<uint8_t>(value.ecw_min()) << ", ";
  os << "ecw_max";
  os << " = " << fidl::ostream::Formatted<uint8_t>(value.ecw_max()) << ", ";
  os << "aifsn";
  os << " = " << fidl::ostream::Formatted<uint8_t>(value.aifsn()) << ", ";
  os << "txop_limit";
  os << " = " << fidl::ostream::Formatted<uint16_t>(value.txop_limit()) << ", ";
  os << "acm";
  os << " = " << fidl::ostream::Formatted<bool>(value.acm()) << ", ";
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::WlanWmmParameters>::Format(std::ostream& os, const ::fuchsia_wlan_common::WlanWmmParameters& value) {
  os << "fuchsia_wlan_common::WlanWmmParameters";
  os << "{ ";
  os << "apsd";
  os << " = " << fidl::ostream::Formatted<bool>(value.apsd()) << ", ";
  os << "ac_be_params";
  os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::WlanWmmAccessCategoryParameters>(value.ac_be_params()) << ", ";
  os << "ac_bk_params";
  os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::WlanWmmAccessCategoryParameters>(value.ac_bk_params()) << ", ";
  os << "ac_vi_params";
  os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::WlanWmmAccessCategoryParameters>(value.ac_vi_params()) << ", ";
  os << "ac_vo_params";
  os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::WlanWmmAccessCategoryParameters>(value.ac_vo_params()) << ", ";
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::WlanChannel>::Format(std::ostream& os, const ::fuchsia_wlan_common::WlanChannel& value) {
  os << "fuchsia_wlan_common::WlanChannel";
  os << "{ ";
  os << "primary";
  os << " = " << fidl::ostream::Formatted<uint8_t>(value.primary()) << ", ";
  os << "cbw";
  os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::ChannelBandwidth>(value.cbw()) << ", ";
  os << "secondary80";
  os << " = " << fidl::ostream::Formatted<uint8_t>(value.secondary80()) << ", ";
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::WlanTxResultEntry>::Format(std::ostream& os, const ::fuchsia_wlan_common::WlanTxResultEntry& value) {
  os << "fuchsia_wlan_common::WlanTxResultEntry";
  os << "{ ";
  os << "tx_vector_idx";
  os << " = " << fidl::ostream::Formatted<uint16_t>(value.tx_vector_idx()) << ", ";
  os << "attempts";
  os << " = " << fidl::ostream::Formatted<uint8_t>(value.attempts()) << ", ";
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::WlanTxResult>::Format(std::ostream& os, const ::fuchsia_wlan_common::WlanTxResult& value) {
  os << "fuchsia_wlan_common::WlanTxResult";
  os << "{ ";
  os << "tx_result_entry";
  os << " = " << fidl::ostream::Formatted<::std::array<::fuchsia_wlan_common::WlanTxResultEntry, 8>>(value.tx_result_entry()) << ", ";
  os << "peer_addr";
  os << " = " << fidl::ostream::Formatted<::std::array<uint8_t, 6>>(value.peer_addr()) << ", ";
  os << "result_code";
  os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::WlanTxResultCode>(value.result_code()) << ", ";
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::BssDescription>::Format(std::ostream& os, const ::fuchsia_wlan_common::BssDescription& value) {
  os << "fuchsia_wlan_common::BssDescription";
  os << "{ ";
  os << "bssid";
  os << " = " << fidl::ostream::Formatted<::std::array<uint8_t, 6>>(value.bssid()) << ", ";
  os << "bss_type";
  os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::BssType>(value.bss_type()) << ", ";
  os << "beacon_period";
  os << " = " << fidl::ostream::Formatted<uint16_t>(value.beacon_period()) << ", ";
  os << "capability_info";
  os << " = " << fidl::ostream::Formatted<uint16_t>(value.capability_info()) << ", ";
  os << "ies";
  os << " = " << fidl::ostream::Formatted<::std::vector<uint8_t>>(value.ies()) << ", ";
  os << "channel";
  os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_ieee80211::WlanChannel>(value.channel()) << ", ";
  os << "rssi_dbm";
  os << " = " << fidl::ostream::Formatted<int8_t>(value.rssi_dbm()) << ", ";
  os << "snr_db";
  os << " = " << fidl::ostream::Formatted<int8_t>(value.snr_db()) << ", ";
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::ScanOffloadExtension>::Format(std::ostream& os, const ::fuchsia_wlan_common::ScanOffloadExtension& value) {
  os << "fuchsia_wlan_common::ScanOffloadExtension";
  os << "{ ";
  if (value.supported().has_value()) {
    os << "supported";
    os << " = " << fidl::ostream::Formatted<bool>(value.supported().value()) << ", ";
  }
  if (value.scan_cancel_supported().has_value()) {
    os << "scan_cancel_supported";
    os << " = " << fidl::ostream::Formatted<bool>(value.scan_cancel_supported().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::ProbeResponseOffloadExtension>::Format(std::ostream& os, const ::fuchsia_wlan_common::ProbeResponseOffloadExtension& value) {
  os << "fuchsia_wlan_common::ProbeResponseOffloadExtension";
  os << "{ ";
  if (value.supported().has_value()) {
    os << "supported";
    os << " = " << fidl::ostream::Formatted<bool>(value.supported().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::DiscoverySupport>::Format(std::ostream& os, const ::fuchsia_wlan_common::DiscoverySupport& value) {
  os << "fuchsia_wlan_common::DiscoverySupport";
  os << "{ ";
  if (value.scan_offload().has_value()) {
    os << "scan_offload";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::ScanOffloadExtension>(value.scan_offload().value()) << ", ";
  }
  if (value.probe_response_offload().has_value()) {
    os << "probe_response_offload";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::ProbeResponseOffloadExtension>(value.probe_response_offload().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::RateSelectionOffloadExtension>::Format(std::ostream& os, const ::fuchsia_wlan_common::RateSelectionOffloadExtension& value) {
  os << "fuchsia_wlan_common::RateSelectionOffloadExtension";
  os << "{ ";
  if (value.supported().has_value()) {
    os << "supported";
    os << " = " << fidl::ostream::Formatted<bool>(value.supported().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::DataPlaneExtension>::Format(std::ostream& os, const ::fuchsia_wlan_common::DataPlaneExtension& value) {
  os << "fuchsia_wlan_common::DataPlaneExtension";
  os << "{ ";
  if (value.data_plane_type().has_value()) {
    os << "data_plane_type";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::DataPlaneType>(value.data_plane_type().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::DeviceExtension>::Format(std::ostream& os, const ::fuchsia_wlan_common::DeviceExtension& value) {
  os << "fuchsia_wlan_common::DeviceExtension";
  os << "{ ";
  if (value.is_synthetic().has_value()) {
    os << "is_synthetic";
    os << " = " << fidl::ostream::Formatted<bool>(value.is_synthetic().value()) << ", ";
  }
  if (value.mac_implementation_type().has_value()) {
    os << "mac_implementation_type";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::MacImplementationType>(value.mac_implementation_type().value()) << ", ";
  }
  if (value.tx_status_report_supported().has_value()) {
    os << "tx_status_report_supported";
    os << " = " << fidl::ostream::Formatted<bool>(value.tx_status_report_supported().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::MacSublayerSupport>::Format(std::ostream& os, const ::fuchsia_wlan_common::MacSublayerSupport& value) {
  os << "fuchsia_wlan_common::MacSublayerSupport";
  os << "{ ";
  if (value.rate_selection_offload().has_value()) {
    os << "rate_selection_offload";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::RateSelectionOffloadExtension>(value.rate_selection_offload().value()) << ", ";
  }
  if (value.data_plane().has_value()) {
    os << "data_plane";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::DataPlaneExtension>(value.data_plane().value()) << ", ";
  }
  if (value.device().has_value()) {
    os << "device";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::DeviceExtension>(value.device().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::SaeFeature>::Format(std::ostream& os, const ::fuchsia_wlan_common::SaeFeature& value) {
  os << "fuchsia_wlan_common::SaeFeature";
  os << "{ ";
  if (value.driver_handler_supported().has_value()) {
    os << "driver_handler_supported";
    os << " = " << fidl::ostream::Formatted<bool>(value.driver_handler_supported().value()) << ", ";
  }
  if (value.sme_handler_supported().has_value()) {
    os << "sme_handler_supported";
    os << " = " << fidl::ostream::Formatted<bool>(value.sme_handler_supported().value()) << ", ";
  }
  if (value.hash_to_element_supported().has_value()) {
    os << "hash_to_element_supported";
    os << " = " << fidl::ostream::Formatted<bool>(value.hash_to_element_supported().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::MfpFeature>::Format(std::ostream& os, const ::fuchsia_wlan_common::MfpFeature& value) {
  os << "fuchsia_wlan_common::MfpFeature";
  os << "{ ";
  if (value.supported().has_value()) {
    os << "supported";
    os << " = " << fidl::ostream::Formatted<bool>(value.supported().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::OweFeature>::Format(std::ostream& os, const ::fuchsia_wlan_common::OweFeature& value) {
  os << "fuchsia_wlan_common::OweFeature";
  os << "{ ";
  if (value.supported().has_value()) {
    os << "supported";
    os << " = " << fidl::ostream::Formatted<bool>(value.supported().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::SecuritySupport>::Format(std::ostream& os, const ::fuchsia_wlan_common::SecuritySupport& value) {
  os << "fuchsia_wlan_common::SecuritySupport";
  os << "{ ";
  if (value.sae().has_value()) {
    os << "sae";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::SaeFeature>(value.sae().value()) << ", ";
  }
  if (value.mfp().has_value()) {
    os << "mfp";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::MfpFeature>(value.mfp().value()) << ", ";
  }
  if (value.owe().has_value()) {
    os << "owe";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::OweFeature>(value.owe().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::DfsFeature>::Format(std::ostream& os, const ::fuchsia_wlan_common::DfsFeature& value) {
  os << "fuchsia_wlan_common::DfsFeature";
  os << "{ ";
  if (value.supported().has_value()) {
    os << "supported";
    os << " = " << fidl::ostream::Formatted<bool>(value.supported().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::SpectrumManagementSupport>::Format(std::ostream& os, const ::fuchsia_wlan_common::SpectrumManagementSupport& value) {
  os << "fuchsia_wlan_common::SpectrumManagementSupport";
  os << "{ ";
  if (value.dfs().has_value()) {
    os << "dfs";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::DfsFeature>(value.dfs().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::ApfPacketFilterSupport>::Format(std::ostream& os, const ::fuchsia_wlan_common::ApfPacketFilterSupport& value) {
  os << "fuchsia_wlan_common::ApfPacketFilterSupport";
  os << "{ ";
  if (value.supported().has_value()) {
    os << "supported";
    os << " = " << fidl::ostream::Formatted<bool>(value.supported().value()) << ", ";
  }
  if (value.version().has_value()) {
    os << "version";
    os << " = " << fidl::ostream::Formatted<int32_t>(value.version().value()) << ", ";
  }
  if (value.max_filter_length().has_value()) {
    os << "max_filter_length";
    os << " = " << fidl::ostream::Formatted<int32_t>(value.max_filter_length().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::JoinBssRequest>::Format(std::ostream& os, const ::fuchsia_wlan_common::JoinBssRequest& value) {
  os << "fuchsia_wlan_common::JoinBssRequest";
  os << "{ ";
  if (value.bssid().has_value()) {
    os << "bssid";
    os << " = " << fidl::ostream::Formatted<::std::array<uint8_t, 6>>(value.bssid().value()) << ", ";
  }
  if (value.bss_type().has_value()) {
    os << "bss_type";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::BssType>(value.bss_type().value()) << ", ";
  }
  if (value.remote().has_value()) {
    os << "remote";
    os << " = " << fidl::ostream::Formatted<bool>(value.remote().value()) << ", ";
  }
  if (value.beacon_period().has_value()) {
    os << "beacon_period";
    os << " = " << fidl::ostream::Formatted<uint16_t>(value.beacon_period().value()) << ", ";
  }
  os << "}";
  return os;
}
std::ostream& fidl::ostream::Formatter<::fuchsia_wlan_common::WlanKeyConfig>::Format(std::ostream& os, const ::fuchsia_wlan_common::WlanKeyConfig& value) {
  os << "fuchsia_wlan_common::WlanKeyConfig";
  os << "{ ";
  if (value.protection().has_value()) {
    os << "protection";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::WlanProtection>(value.protection().value()) << ", ";
  }
  if (value.cipher_oui().has_value()) {
    os << "cipher_oui";
    os << " = " << fidl::ostream::Formatted<::std::array<uint8_t, 3>>(value.cipher_oui().value()) << ", ";
  }
  if (value.cipher_type().has_value()) {
    os << "cipher_type";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_ieee80211::CipherSuiteType>(value.cipher_type().value()) << ", ";
  }
  if (value.key_type().has_value()) {
    os << "key_type";
    os << " = " << fidl::ostream::Formatted<::fuchsia_wlan_common::WlanKeyType>(value.key_type().value()) << ", ";
  }
  if (value.peer_addr().has_value()) {
    os << "peer_addr";
    os << " = " << fidl::ostream::Formatted<::std::array<uint8_t, 6>>(value.peer_addr().value()) << ", ";
  }
  if (value.key_idx().has_value()) {
    os << "key_idx";
    os << " = " << fidl::ostream::Formatted<uint8_t>(value.key_idx().value()) << ", ";
  }
  if (value.key().has_value()) {
    os << "key";
    os << " = " << fidl::ostream::Formatted<::std::vector<uint8_t>>(value.key().value()) << ", ";
  }
  if (value.rsc().has_value()) {
    os << "rsc";
    os << " = " << fidl::ostream::Formatted<uint64_t>(value.rsc().value()) << ", ";
  }
  os << "}";
  return os;
}

namespace fuchsia_wlan_common {

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::WlanKeyType& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::WlanKeyType>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::WlanWmmAccessCategoryParameters& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::WlanWmmAccessCategoryParameters>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::WlanWmmParameters& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::WlanWmmParameters>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::ScanOffloadExtension& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::ScanOffloadExtension>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::ProbeResponseOffloadExtension& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::ProbeResponseOffloadExtension>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::DiscoverySupport& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::DiscoverySupport>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::RateSelectionOffloadExtension& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::RateSelectionOffloadExtension>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::DataPlaneType& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::DataPlaneType>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::DataPlaneExtension& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::DataPlaneExtension>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::MacImplementationType& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::MacImplementationType>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::DeviceExtension& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::DeviceExtension>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::MacSublayerSupport& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::MacSublayerSupport>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::SaeFeature& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::SaeFeature>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::MfpFeature& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::MfpFeature>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::OweFeature& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::OweFeature>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::SecuritySupport& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::SecuritySupport>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::DfsFeature& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::DfsFeature>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::SpectrumManagementSupport& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::SpectrumManagementSupport>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::ApfPacketFilterSupport& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::ApfPacketFilterSupport>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::ChannelBandwidth& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::ChannelBandwidth>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::WlanChannel& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::WlanChannel>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::WlanPhyType& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::WlanPhyType>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::WlanMacRole& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::WlanMacRole>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::ScanType& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::ScanType>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::GuardInterval& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::GuardInterval>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::PowerSaveType& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::PowerSaveType>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::WlanTxResultEntry& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::WlanTxResultEntry>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::WlanTxResultCode& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::WlanTxResultCode>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::WlanTxResult& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::WlanTxResult>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::WlanSoftmacHardwareCapabilityBit& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::WlanSoftmacHardwareCapabilityBit>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::BssType& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::BssType>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::JoinBssRequest& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::JoinBssRequest>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::WlanProtection& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::WlanProtection>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::WlanKeyConfig& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::WlanKeyConfig>::Format(os, value);
}

std::ostream& operator<<(std::ostream& os, const ::fuchsia_wlan_common::BssDescription& value) {
  return fidl::ostream::Formatter<::fuchsia_wlan_common::BssDescription>::Format(os, value);
}

#pragma clang diagnostic pop

}  // namespace fuchsia_wlan_common
