// WARNING: This file is machine generated by fidlgen.

#include <fidl/fuchsia.thermal/cpp/natural_types.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wshadow"

void fidl::internal::NaturalCodingTraits<::fuchsia_thermal::SetTemperatureOverrideError, ::fidl::internal::NaturalCodingConstraintEmpty>::Encode(
    fidl::internal::NaturalEncoder* encoder, ::fuchsia_thermal::SetTemperatureOverrideError* value, size_t offset, size_t recursion_depth) {
  *encoder->template GetPtr<::fuchsia_thermal::SetTemperatureOverrideError>(offset) = *value;
}

void fidl::internal::NaturalCodingTraits<::fuchsia_thermal::SetTemperatureOverrideError, ::fidl::internal::NaturalCodingConstraintEmpty>::Decode(
    fidl::internal::NaturalDecoder* decoder, ::fuchsia_thermal::SetTemperatureOverrideError* value, size_t offset, size_t recursion_depth) {
  *value = *decoder->template GetPtr<::fuchsia_thermal::SetTemperatureOverrideError>(offset);
}

void fidl::internal::NaturalCodingTraits<::fuchsia_thermal::ClearTemperatureOverrideError, ::fidl::internal::NaturalCodingConstraintEmpty>::Encode(
    fidl::internal::NaturalEncoder* encoder, ::fuchsia_thermal::ClearTemperatureOverrideError* value, size_t offset, size_t recursion_depth) {
  *encoder->template GetPtr<::fuchsia_thermal::ClearTemperatureOverrideError>(offset) = *value;
}

void fidl::internal::NaturalCodingTraits<::fuchsia_thermal::ClearTemperatureOverrideError, ::fidl::internal::NaturalCodingConstraintEmpty>::Decode(
    fidl::internal::NaturalDecoder* decoder, ::fuchsia_thermal::ClearTemperatureOverrideError* value, size_t offset, size_t recursion_depth) {
  *value = *decoder->template GetPtr<::fuchsia_thermal::ClearTemperatureOverrideError>(offset);
}

void fidl::internal::NaturalCodingTraits<::fuchsia_thermal::ConnectError, ::fidl::internal::NaturalCodingConstraintEmpty>::Encode(
    fidl::internal::NaturalEncoder* encoder, ::fuchsia_thermal::ConnectError* value, size_t offset, size_t recursion_depth) {
  *encoder->template GetPtr<::fuchsia_thermal::ConnectError>(offset) = *value;
}

void fidl::internal::NaturalCodingTraits<::fuchsia_thermal::ConnectError, ::fidl::internal::NaturalCodingConstraintEmpty>::Decode(
    fidl::internal::NaturalDecoder* decoder, ::fuchsia_thermal::ConnectError* value, size_t offset, size_t recursion_depth) {
  *value = *decoder->template GetPtr<::fuchsia_thermal::ConnectError>(offset);
}

#if __FIDL_SUPPORT_HANDLES

::fuchsia_thermal::ClientStateConnectorConnectRequest::ClientStateConnectorConnectRequest(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_thermal::ClientStateConnectorConnectRequest::ClientStateConnectorConnectRequest(::std::string client_type, ::fidl::ServerEnd<::fuchsia_thermal::ClientStateWatcher> watcher) noexcept
    : storage_({.client_type = std::move(client_type),
                .watcher = std::move(watcher)}) {}

::fuchsia_thermal::ClientStateConnectorConnectRequest::ClientStateConnectorConnectRequest(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : ClientStateConnectorConnectRequest(Storage_{
                                                                                                                                                            .client_type = {},
                                                                                                                                                            .watcher = {},
                                                                                                                                                        }) {}
const ::std::string&
fuchsia_thermal::ClientStateConnectorConnectRequest::client_type() const {
  return storage_.client_type;
}

::std::string& ::fuchsia_thermal::ClientStateConnectorConnectRequest::client_type() {
  return storage_.client_type;
}

::fuchsia_thermal::ClientStateConnectorConnectRequest& ::fuchsia_thermal::ClientStateConnectorConnectRequest::client_type(::std::string value) {
  storage_.client_type = std::move(value);
  return *this;
}
const ::fidl::ServerEnd<::fuchsia_thermal::ClientStateWatcher>&
fuchsia_thermal::ClientStateConnectorConnectRequest::watcher() const {
  return storage_.watcher;
}

::fidl::ServerEnd<::fuchsia_thermal::ClientStateWatcher>& ::fuchsia_thermal::ClientStateConnectorConnectRequest::watcher() {
  return storage_.watcher;
}

::fuchsia_thermal::ClientStateConnectorConnectRequest& ::fuchsia_thermal::ClientStateConnectorConnectRequest::watcher(::fidl::ServerEnd<::fuchsia_thermal::ClientStateWatcher> value) {
  storage_.watcher = std::move(value);
  return *this;
}

#endif  // __FIDL_SUPPORT_HANDLES

::fuchsia_thermal::ClientStateWatcherWatchResponse::ClientStateWatcherWatchResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_thermal::ClientStateWatcherWatchResponse::ClientStateWatcherWatchResponse(uint64_t state) noexcept
    : storage_({.state = std::move(state)}) {}

::fuchsia_thermal::ClientStateWatcherWatchResponse::ClientStateWatcherWatchResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : ClientStateWatcherWatchResponse(Storage_{
                                                                                                                                                      .state = {},
                                                                                                                                                  }) {}
::fuchsia_thermal::ClientStateWatcherWatchResponse::ClientStateWatcherWatchResponse(const ::fuchsia_thermal::ClientStateWatcherWatchResponse& other) noexcept : ::fuchsia_thermal::ClientStateWatcherWatchResponse(other.CloneStorage_()) {}

::fuchsia_thermal::ClientStateWatcherWatchResponse& fuchsia_thermal::ClientStateWatcherWatchResponse::operator=(const ::fuchsia_thermal::ClientStateWatcherWatchResponse& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_thermal::ClientStateWatcherWatchResponse::operator==(const ClientStateWatcherWatchResponse& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::ClientStateWatcherWatchResponse, 8>::Equal(this, &other);
}

bool fuchsia_thermal::ClientStateWatcherWatchResponse::operator!=(const ClientStateWatcherWatchResponse& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::ClientStateWatcherWatchResponse, 8>::Equal(this, &other);
}

::fuchsia_thermal::ClientStateWatcherWatchResponse::Storage_ fuchsia_thermal::ClientStateWatcherWatchResponse::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.state)};
}
uint64_t
fuchsia_thermal::ClientStateWatcherWatchResponse::state() const {
  return storage_.state;
}

uint64_t& ::fuchsia_thermal::ClientStateWatcherWatchResponse::state() {
  return storage_.state;
}

::fuchsia_thermal::ClientStateWatcherWatchResponse& ::fuchsia_thermal::ClientStateWatcherWatchResponse::state(uint64_t value) {
  storage_.state = std::move(value);
  return *this;
}

::fuchsia_thermal::SensorManagerListSensorsResponse::SensorManagerListSensorsResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_thermal::SensorManagerListSensorsResponse::SensorManagerListSensorsResponse(::std::vector<::fuchsia_thermal::SensorInfo> sensors) noexcept
    : storage_({.sensors = std::move(sensors)}) {}

::fuchsia_thermal::SensorManagerListSensorsResponse::SensorManagerListSensorsResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : SensorManagerListSensorsResponse(Storage_{
                                                                                                                                                        .sensors = {},
                                                                                                                                                    }) {}
::fuchsia_thermal::SensorManagerListSensorsResponse::SensorManagerListSensorsResponse(const ::fuchsia_thermal::SensorManagerListSensorsResponse& other) noexcept : ::fuchsia_thermal::SensorManagerListSensorsResponse(other.CloneStorage_()) {}

::fuchsia_thermal::SensorManagerListSensorsResponse& fuchsia_thermal::SensorManagerListSensorsResponse::operator=(const ::fuchsia_thermal::SensorManagerListSensorsResponse& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_thermal::SensorManagerListSensorsResponse::operator==(const SensorManagerListSensorsResponse& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::SensorManagerListSensorsResponse, 16>::Equal(this, &other);
}

bool fuchsia_thermal::SensorManagerListSensorsResponse::operator!=(const SensorManagerListSensorsResponse& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::SensorManagerListSensorsResponse, 16>::Equal(this, &other);
}

::fuchsia_thermal::SensorManagerListSensorsResponse::Storage_ fuchsia_thermal::SensorManagerListSensorsResponse::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.sensors)};
}
const ::std::vector<::fuchsia_thermal::SensorInfo>&
fuchsia_thermal::SensorManagerListSensorsResponse::sensors() const {
  return storage_.sensors;
}

::std::vector<::fuchsia_thermal::SensorInfo>& ::fuchsia_thermal::SensorManagerListSensorsResponse::sensors() {
  return storage_.sensors;
}

::fuchsia_thermal::SensorManagerListSensorsResponse& ::fuchsia_thermal::SensorManagerListSensorsResponse::sensors(::std::vector<::fuchsia_thermal::SensorInfo> value) {
  storage_.sensors = std::move(value);
  return *this;
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::SensorManagerSetTemperatureOverrideRequest(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::SensorManagerSetTemperatureOverrideRequest(::std::string name, float override_temperature) noexcept
    : storage_({.name = std::move(name),
                .override_temperature = std::move(override_temperature)}) {}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::SensorManagerSetTemperatureOverrideRequest(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : SensorManagerSetTemperatureOverrideRequest(Storage_{
                                                                                                                                                                            .name = {},
                                                                                                                                                                            .override_temperature = {},
                                                                                                                                                                        }) {}
::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::SensorManagerSetTemperatureOverrideRequest(const ::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest& other) noexcept : ::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest(other.CloneStorage_()) {}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest& fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::operator=(const ::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::operator==(const SensorManagerSetTemperatureOverrideRequest& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest, 24>::Equal(this, &other);
}

bool fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::operator!=(const SensorManagerSetTemperatureOverrideRequest& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest, 24>::Equal(this, &other);
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::Storage_ fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.name),
      ::fidl::internal::NaturalClone(storage_.override_temperature)};
}
const ::std::string&
fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::name() const {
  return storage_.name;
}

::std::string& ::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::name() {
  return storage_.name;
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest& ::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::name(::std::string value) {
  storage_.name = std::move(value);
  return *this;
}
float fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::override_temperature() const {
  return storage_.override_temperature;
}

float& ::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::override_temperature() {
  return storage_.override_temperature;
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest& ::fuchsia_thermal::SensorManagerSetTemperatureOverrideRequest::override_temperature(float value) {
  storage_.override_temperature = std::move(value);
  return *this;
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse::SensorManagerSetTemperatureOverrideResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse::SensorManagerSetTemperatureOverrideResponse(uint8_t __reserved) noexcept
    : storage_({.__reserved = std::move(__reserved)}) {}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse::SensorManagerSetTemperatureOverrideResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : SensorManagerSetTemperatureOverrideResponse(Storage_{
                                                                                                                                                                              .__reserved = 0u,
                                                                                                                                                                          }) {}
::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse::SensorManagerSetTemperatureOverrideResponse(const ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse& other) noexcept : ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse(other.CloneStorage_()) {}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse& fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse::operator=(const ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse::operator==(const SensorManagerSetTemperatureOverrideResponse& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse, 1>::Equal(this, &other);
}

bool fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse::operator!=(const SensorManagerSetTemperatureOverrideResponse& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse, 1>::Equal(this, &other);
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse::Storage_ fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.__reserved)};
}
uint8_t
fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse::__reserved() const {
  return storage_.__reserved;
}

uint8_t& ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse::__reserved() {
  return storage_.__reserved;
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse& ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse::__reserved(uint8_t value) {
  storage_.__reserved = std::move(value);
  return *this;
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest::SensorManagerClearTemperatureOverrideRequest(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest::SensorManagerClearTemperatureOverrideRequest(::std::string name) noexcept
    : storage_({.name = std::move(name)}) {}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest::SensorManagerClearTemperatureOverrideRequest(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : SensorManagerClearTemperatureOverrideRequest(Storage_{
                                                                                                                                                                                .name = {},
                                                                                                                                                                            }) {}
::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest::SensorManagerClearTemperatureOverrideRequest(const ::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest& other) noexcept : ::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest(other.CloneStorage_()) {}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest& fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest::operator=(const ::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest::operator==(const SensorManagerClearTemperatureOverrideRequest& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest, 16>::Equal(this, &other);
}

bool fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest::operator!=(const SensorManagerClearTemperatureOverrideRequest& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest, 16>::Equal(this, &other);
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest::Storage_ fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.name)};
}
const ::std::string&
fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest::name() const {
  return storage_.name;
}

::std::string& ::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest::name() {
  return storage_.name;
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest& ::fuchsia_thermal::SensorManagerClearTemperatureOverrideRequest::name(::std::string value) {
  storage_.name = std::move(value);
  return *this;
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse::SensorManagerClearTemperatureOverrideResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse::SensorManagerClearTemperatureOverrideResponse(uint8_t __reserved) noexcept
    : storage_({.__reserved = std::move(__reserved)}) {}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse::SensorManagerClearTemperatureOverrideResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : SensorManagerClearTemperatureOverrideResponse(Storage_{
                                                                                                                                                                                  .__reserved = 0u,
                                                                                                                                                                              }) {}
::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse::SensorManagerClearTemperatureOverrideResponse(const ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse& other) noexcept : ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse(other.CloneStorage_()) {}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse& fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse::operator=(const ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse::operator==(const SensorManagerClearTemperatureOverrideResponse& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse, 1>::Equal(this, &other);
}

bool fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse::operator!=(const SensorManagerClearTemperatureOverrideResponse& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse, 1>::Equal(this, &other);
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse::Storage_ fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.__reserved)};
}
uint8_t
fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse::__reserved() const {
  return storage_.__reserved;
}

uint8_t& ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse::__reserved() {
  return storage_.__reserved;
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse& ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse::__reserved(uint8_t value) {
  storage_.__reserved = std::move(value);
  return *this;
}

::fuchsia_thermal::SensorManagerConnectResponse::SensorManagerConnectResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_thermal::SensorManagerConnectResponse::SensorManagerConnectResponse(uint8_t __reserved) noexcept
    : storage_({.__reserved = std::move(__reserved)}) {}

::fuchsia_thermal::SensorManagerConnectResponse::SensorManagerConnectResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : SensorManagerConnectResponse(Storage_{
                                                                                                                                                .__reserved = 0u,
                                                                                                                                            }) {}
::fuchsia_thermal::SensorManagerConnectResponse::SensorManagerConnectResponse(const ::fuchsia_thermal::SensorManagerConnectResponse& other) noexcept : ::fuchsia_thermal::SensorManagerConnectResponse(other.CloneStorage_()) {}

::fuchsia_thermal::SensorManagerConnectResponse& fuchsia_thermal::SensorManagerConnectResponse::operator=(const ::fuchsia_thermal::SensorManagerConnectResponse& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_thermal::SensorManagerConnectResponse::operator==(const SensorManagerConnectResponse& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::SensorManagerConnectResponse, 1>::Equal(this, &other);
}

bool fuchsia_thermal::SensorManagerConnectResponse::operator!=(const SensorManagerConnectResponse& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_thermal::SensorManagerConnectResponse, 1>::Equal(this, &other);
}

::fuchsia_thermal::SensorManagerConnectResponse::Storage_ fuchsia_thermal::SensorManagerConnectResponse::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.__reserved)};
}
uint8_t
fuchsia_thermal::SensorManagerConnectResponse::__reserved() const {
  return storage_.__reserved;
}

uint8_t& ::fuchsia_thermal::SensorManagerConnectResponse::__reserved() {
  return storage_.__reserved;
}

::fuchsia_thermal::SensorManagerConnectResponse& ::fuchsia_thermal::SensorManagerConnectResponse::__reserved(uint8_t value) {
  storage_.__reserved = std::move(value);
  return *this;
}

::fuchsia_thermal::SensorInfo::SensorInfo(::fuchsia_thermal::SensorInfo::Storage_ storage) noexcept : storage_(std::move(storage)) {}

::fuchsia_thermal::SensorInfo::SensorInfo(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : SensorInfo(Storage_{}) {}

::fuchsia_thermal::SensorInfo::SensorInfo(const ::fuchsia_thermal::SensorInfo& other) noexcept : SensorInfo(other.CloneStorage_()) {}

::fuchsia_thermal::SensorInfo& ::fuchsia_thermal::SensorInfo::operator=(const ::fuchsia_thermal::SensorInfo& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_thermal::SensorInfo::operator==(const SensorInfo& other) const noexcept {
  return ::fidl::internal::NaturalTableCodingTraits<::fuchsia_thermal::SensorInfo>::Equal(this, &other);
}
bool fuchsia_thermal::SensorInfo::operator!=(const SensorInfo& other) const noexcept {
  return !::fidl::internal::NaturalTableCodingTraits<::fuchsia_thermal::SensorInfo>::Equal(this, &other);
}

::fuchsia_thermal::SensorInfo::Storage_ fuchsia_thermal::SensorInfo::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.name)};
}

bool fuchsia_thermal::SensorInfo::IsEmpty() const {
  return !(storage_.name.has_value());
}
const std::optional<::std::string>& fuchsia_thermal::SensorInfo::name() const {
  return storage_.name;
}

::std::optional<::std::string>& fuchsia_thermal::SensorInfo::name() {
  return storage_.name;
}

::fuchsia_thermal::SensorInfo& fuchsia_thermal::SensorInfo::name(std::optional<::std::string> value) {
  storage_.name = std::move(value);
  return *this;
}
#if __FIDL_SUPPORT_HANDLES

::fuchsia_thermal::SensorManagerConnectRequest::SensorManagerConnectRequest(::fuchsia_thermal::SensorManagerConnectRequest::Storage_ storage) noexcept : storage_(std::move(storage)) {}

::fuchsia_thermal::SensorManagerConnectRequest::SensorManagerConnectRequest(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : SensorManagerConnectRequest(Storage_{}) {}

bool fuchsia_thermal::SensorManagerConnectRequest::IsEmpty() const {
  return !(storage_.name.has_value() || storage_.server_end.has_value());
}
const std::optional<::std::string>& fuchsia_thermal::SensorManagerConnectRequest::name() const {
  return storage_.name;
}

::std::optional<::std::string>& fuchsia_thermal::SensorManagerConnectRequest::name() {
  return storage_.name;
}

::fuchsia_thermal::SensorManagerConnectRequest& fuchsia_thermal::SensorManagerConnectRequest::name(std::optional<::std::string> value) {
  storage_.name = std::move(value);
  return *this;
}
const std::optional<::fuchsia_thermal::SensorServer>& fuchsia_thermal::SensorManagerConnectRequest::server_end() const {
  return storage_.server_end;
}

::std::optional<::fuchsia_thermal::SensorServer>& fuchsia_thermal::SensorManagerConnectRequest::server_end() {
  return storage_.server_end;
}

::fuchsia_thermal::SensorManagerConnectRequest& fuchsia_thermal::SensorManagerConnectRequest::server_end(std::optional<::fuchsia_thermal::SensorServer> value) {
  storage_.server_end = std::move(value);
  return *this;
}

::fuchsia_thermal::SensorServer::SensorServer(SensorServer&& other) noexcept : SensorServer(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag{}) {
  *storage_ = std::move(*other.storage_);
}

::fuchsia_thermal::SensorServer& ::fuchsia_thermal::SensorServer::operator=(SensorServer&& other) noexcept {
  if (this != &other) {
    *storage_ = std::move(*other.storage_);
  }
  return *this;
}

::fuchsia_thermal::SensorServer::SensorServer(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag)
    : storage_(std::make_shared<Storage_>()) {}

::fuchsia_thermal::SensorServer::SensorServer(std::shared_ptr<Storage_> storage) : storage_(std::move(storage)) {}

::fuchsia_thermal::SensorServer::Tag fuchsia_thermal::SensorServer::Which() const {
  return SensorServer::IndexToTag(storage_->index()).value();
}

size_t fuchsia_thermal::SensorServer::TagToIndex(::fidl::internal::NaturalDecoder* decoder, ::fuchsia_thermal::SensorServer::Tag tag) {
  switch (tag) {
    case ::fuchsia_thermal::SensorServer::Tag::kTemperature:
      return 1;
    default: {
      return 0;
    }
  }
}

std::optional<::fuchsia_thermal::SensorServer::Tag> fuchsia_thermal::SensorServer::IndexToTag(size_t index) {
  switch (index) {
    case 1:
      return ::fuchsia_thermal::SensorServer::Tag::kTemperature;
    default:
      return ::fuchsia_thermal::SensorServer::Tag::_do_not_handle_this__write_a_default_case_instead;
  }
}

bool fuchsia_thermal::SensorServer::IsUnknown() const {
  return Which() == ::fuchsia_thermal::SensorServer::Tag::_do_not_handle_this__write_a_default_case_instead;
}
::fuchsia_thermal::SensorServer fuchsia_thermal::SensorServer::WithTemperature(::fidl::ServerEnd<::fuchsia_hardware_temperature::Device> val) {
  return SensorServer(std::make_shared<Storage_>(
      std::in_place_index_t<1>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<1, ::fuchsia_thermal::SensorServer::Storage_> fuchsia_thermal::SensorServer::temperature() const {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<1, ::fuchsia_thermal::SensorServer::Storage_> fuchsia_thermal::SensorServer::temperature() {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fuchsia_thermal::SensorServer& fuchsia_thermal::SensorServer::temperature(::fidl::ServerEnd<::fuchsia_hardware_temperature::Device> value) {
  storage_->emplace<1>(std::move(value));
  return *this;
}

#endif  // __FIDL_SUPPORT_HANDLES

::fuchsia_thermal::SensorManagerListSensorsResult::SensorManagerListSensorsResult(SensorManagerListSensorsResult&& other) noexcept : SensorManagerListSensorsResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag{}) {
  *storage_ = std::move(*other.storage_);
}

::fuchsia_thermal::SensorManagerListSensorsResult& ::fuchsia_thermal::SensorManagerListSensorsResult::operator=(SensorManagerListSensorsResult&& other) noexcept {
  if (this != &other) {
    *storage_ = std::move(*other.storage_);
  }
  return *this;
}

::fuchsia_thermal::SensorManagerListSensorsResult::SensorManagerListSensorsResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag)
    : storage_(std::make_shared<Storage_>()) {}

::fuchsia_thermal::SensorManagerListSensorsResult::SensorManagerListSensorsResult(std::shared_ptr<Storage_> storage) : storage_(std::move(storage)) {}

::fuchsia_thermal::SensorManagerListSensorsResult::Tag fuchsia_thermal::SensorManagerListSensorsResult::Which() const {
  return SensorManagerListSensorsResult::IndexToTag(storage_->index()).value();
}

size_t fuchsia_thermal::SensorManagerListSensorsResult::TagToIndex(::fidl::internal::NaturalDecoder* decoder, ::fuchsia_thermal::SensorManagerListSensorsResult::Tag tag) {
  switch (tag) {
    case ::fuchsia_thermal::SensorManagerListSensorsResult::Tag::kResponse:
      return 1;
    case ::fuchsia_thermal::SensorManagerListSensorsResult::Tag::kFrameworkErr:
      return 2;
    default: {
      decoder->SetError(::fidl::internal::kCodingErrorUnknownUnionTag);
      return 0;
    }
  }
}

std::optional<::fuchsia_thermal::SensorManagerListSensorsResult::Tag> fuchsia_thermal::SensorManagerListSensorsResult::IndexToTag(size_t index) {
  switch (index) {
    case 1:
      return ::fuchsia_thermal::SensorManagerListSensorsResult::Tag::kResponse;
    case 2:
      return ::fuchsia_thermal::SensorManagerListSensorsResult::Tag::kFrameworkErr;
    default:
      return std::nullopt;
  }
}

::fuchsia_thermal::SensorManagerListSensorsResult::SensorManagerListSensorsResult(const SensorManagerListSensorsResult& other) noexcept : SensorManagerListSensorsResult(other.CloneStorage_()) {}

::fuchsia_thermal::SensorManagerListSensorsResult& fuchsia_thermal::SensorManagerListSensorsResult::operator=(const SensorManagerListSensorsResult& other) noexcept {
  if (this != &other) {
    storage_ = other.CloneStorage_();
  }
  return *this;
}

bool fuchsia_thermal::SensorManagerListSensorsResult::operator==(const SensorManagerListSensorsResult& other) const noexcept {
  return *storage_ == *other.storage_;
}
bool fuchsia_thermal::SensorManagerListSensorsResult::operator!=(const SensorManagerListSensorsResult& other) const noexcept {
  return *storage_ != *other.storage_;
}

std::shared_ptr<::fuchsia_thermal::SensorManagerListSensorsResult::Storage_> fuchsia_thermal::SensorManagerListSensorsResult::CloneStorage_() const {
  const Storage_& storage = *storage_;
  switch (storage_->index()) {
    case 1:
      return std::make_shared<Storage_>(
          std::in_place_index<1>,
          ::fidl::internal::NaturalClone(std::get<1>(storage)));
    case 2:
      return std::make_shared<Storage_>(
          std::in_place_index<2>,
          ::fidl::internal::NaturalClone(std::get<2>(storage)));
    default:
      return std::make_shared<Storage_>();
  }
}
::fuchsia_thermal::SensorManagerListSensorsResult fuchsia_thermal::SensorManagerListSensorsResult::WithResponse(::fuchsia_thermal::SensorManagerListSensorsResponse val) {
  return SensorManagerListSensorsResult(std::make_shared<Storage_>(
      std::in_place_index_t<1>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<1, ::fuchsia_thermal::SensorManagerListSensorsResult::Storage_> fuchsia_thermal::SensorManagerListSensorsResult::response() const {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<1, ::fuchsia_thermal::SensorManagerListSensorsResult::Storage_> fuchsia_thermal::SensorManagerListSensorsResult::response() {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fuchsia_thermal::SensorManagerListSensorsResult& fuchsia_thermal::SensorManagerListSensorsResult::response(::fuchsia_thermal::SensorManagerListSensorsResponse value) {
  storage_->emplace<1>(std::move(value));
  return *this;
}
::fuchsia_thermal::SensorManagerListSensorsResult fuchsia_thermal::SensorManagerListSensorsResult::WithFrameworkErr(::fidl::internal::FrameworkErr val) {
  return SensorManagerListSensorsResult(std::make_shared<Storage_>(
      std::in_place_index_t<2>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<2, ::fuchsia_thermal::SensorManagerListSensorsResult::Storage_> fuchsia_thermal::SensorManagerListSensorsResult::framework_err() const {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<2, ::fuchsia_thermal::SensorManagerListSensorsResult::Storage_> fuchsia_thermal::SensorManagerListSensorsResult::framework_err() {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fuchsia_thermal::SensorManagerListSensorsResult& fuchsia_thermal::SensorManagerListSensorsResult::framework_err(::fidl::internal::FrameworkErr value) {
  storage_->emplace<2>(std::move(value));
  return *this;
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::SensorManagerSetTemperatureOverrideResult(SensorManagerSetTemperatureOverrideResult&& other) noexcept : SensorManagerSetTemperatureOverrideResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag{}) {
  *storage_ = std::move(*other.storage_);
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult& ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::operator=(SensorManagerSetTemperatureOverrideResult&& other) noexcept {
  if (this != &other) {
    *storage_ = std::move(*other.storage_);
  }
  return *this;
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::SensorManagerSetTemperatureOverrideResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag)
    : storage_(std::make_shared<Storage_>()) {}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::SensorManagerSetTemperatureOverrideResult(std::shared_ptr<Storage_> storage) : storage_(std::move(storage)) {}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Tag fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Which() const {
  return SensorManagerSetTemperatureOverrideResult::IndexToTag(storage_->index()).value();
}

size_t fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::TagToIndex(::fidl::internal::NaturalDecoder* decoder, ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Tag tag) {
  switch (tag) {
    case ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Tag::kResponse:
      return 1;
    case ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Tag::kErr:
      return 2;
    case ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Tag::kFrameworkErr:
      return 3;
    default: {
      decoder->SetError(::fidl::internal::kCodingErrorUnknownUnionTag);
      return 0;
    }
  }
}

std::optional<::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Tag> fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::IndexToTag(size_t index) {
  switch (index) {
    case 1:
      return ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Tag::kResponse;
    case 2:
      return ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Tag::kErr;
    case 3:
      return ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Tag::kFrameworkErr;
    default:
      return std::nullopt;
  }
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::SensorManagerSetTemperatureOverrideResult(const SensorManagerSetTemperatureOverrideResult& other) noexcept : SensorManagerSetTemperatureOverrideResult(other.CloneStorage_()) {}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult& fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::operator=(const SensorManagerSetTemperatureOverrideResult& other) noexcept {
  if (this != &other) {
    storage_ = other.CloneStorage_();
  }
  return *this;
}

bool fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::operator==(const SensorManagerSetTemperatureOverrideResult& other) const noexcept {
  return *storage_ == *other.storage_;
}
bool fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::operator!=(const SensorManagerSetTemperatureOverrideResult& other) const noexcept {
  return *storage_ != *other.storage_;
}

std::shared_ptr<::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::CloneStorage_() const {
  const Storage_& storage = *storage_;
  switch (storage_->index()) {
    case 1:
      return std::make_shared<Storage_>(
          std::in_place_index<1>,
          ::fidl::internal::NaturalClone(std::get<1>(storage)));
    case 2:
      return std::make_shared<Storage_>(
          std::in_place_index<2>,
          ::fidl::internal::NaturalClone(std::get<2>(storage)));
    case 3:
      return std::make_shared<Storage_>(
          std::in_place_index<3>,
          ::fidl::internal::NaturalClone(std::get<3>(storage)));
    default:
      return std::make_shared<Storage_>();
  }
}
::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::WithResponse(::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse val) {
  return SensorManagerSetTemperatureOverrideResult(std::make_shared<Storage_>(
      std::in_place_index_t<1>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<1, ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::response() const {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<1, ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::response() {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult& fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::response(::fuchsia_thermal::SensorManagerSetTemperatureOverrideResponse value) {
  storage_->emplace<1>(std::move(value));
  return *this;
}
::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::WithErr(::fuchsia_thermal::SetTemperatureOverrideError val) {
  return SensorManagerSetTemperatureOverrideResult(std::make_shared<Storage_>(
      std::in_place_index_t<2>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<2, ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::err() const {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<2, ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::err() {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult& fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::err(::fuchsia_thermal::SetTemperatureOverrideError value) {
  storage_->emplace<2>(std::move(value));
  return *this;
}
::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::WithFrameworkErr(::fidl::internal::FrameworkErr val) {
  return SensorManagerSetTemperatureOverrideResult(std::make_shared<Storage_>(
      std::in_place_index_t<3>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<3, ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::framework_err() const {
  return ::fidl::internal::UnionMemberView<3, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<3, ::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::framework_err() {
  return ::fidl::internal::UnionMemberView<3, Storage_>(storage_);
}

::fuchsia_thermal::SensorManagerSetTemperatureOverrideResult& fuchsia_thermal::SensorManagerSetTemperatureOverrideResult::framework_err(::fidl::internal::FrameworkErr value) {
  storage_->emplace<3>(std::move(value));
  return *this;
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::SensorManagerClearTemperatureOverrideResult(SensorManagerClearTemperatureOverrideResult&& other) noexcept : SensorManagerClearTemperatureOverrideResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag{}) {
  *storage_ = std::move(*other.storage_);
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult& ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::operator=(SensorManagerClearTemperatureOverrideResult&& other) noexcept {
  if (this != &other) {
    *storage_ = std::move(*other.storage_);
  }
  return *this;
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::SensorManagerClearTemperatureOverrideResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag)
    : storage_(std::make_shared<Storage_>()) {}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::SensorManagerClearTemperatureOverrideResult(std::shared_ptr<Storage_> storage) : storage_(std::move(storage)) {}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Tag fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Which() const {
  return SensorManagerClearTemperatureOverrideResult::IndexToTag(storage_->index()).value();
}

size_t fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::TagToIndex(::fidl::internal::NaturalDecoder* decoder, ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Tag tag) {
  switch (tag) {
    case ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Tag::kResponse:
      return 1;
    case ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Tag::kErr:
      return 2;
    case ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Tag::kFrameworkErr:
      return 3;
    default: {
      decoder->SetError(::fidl::internal::kCodingErrorUnknownUnionTag);
      return 0;
    }
  }
}

std::optional<::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Tag> fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::IndexToTag(size_t index) {
  switch (index) {
    case 1:
      return ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Tag::kResponse;
    case 2:
      return ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Tag::kErr;
    case 3:
      return ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Tag::kFrameworkErr;
    default:
      return std::nullopt;
  }
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::SensorManagerClearTemperatureOverrideResult(const SensorManagerClearTemperatureOverrideResult& other) noexcept : SensorManagerClearTemperatureOverrideResult(other.CloneStorage_()) {}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult& fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::operator=(const SensorManagerClearTemperatureOverrideResult& other) noexcept {
  if (this != &other) {
    storage_ = other.CloneStorage_();
  }
  return *this;
}

bool fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::operator==(const SensorManagerClearTemperatureOverrideResult& other) const noexcept {
  return *storage_ == *other.storage_;
}
bool fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::operator!=(const SensorManagerClearTemperatureOverrideResult& other) const noexcept {
  return *storage_ != *other.storage_;
}

std::shared_ptr<::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::CloneStorage_() const {
  const Storage_& storage = *storage_;
  switch (storage_->index()) {
    case 1:
      return std::make_shared<Storage_>(
          std::in_place_index<1>,
          ::fidl::internal::NaturalClone(std::get<1>(storage)));
    case 2:
      return std::make_shared<Storage_>(
          std::in_place_index<2>,
          ::fidl::internal::NaturalClone(std::get<2>(storage)));
    case 3:
      return std::make_shared<Storage_>(
          std::in_place_index<3>,
          ::fidl::internal::NaturalClone(std::get<3>(storage)));
    default:
      return std::make_shared<Storage_>();
  }
}
::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::WithResponse(::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse val) {
  return SensorManagerClearTemperatureOverrideResult(std::make_shared<Storage_>(
      std::in_place_index_t<1>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<1, ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::response() const {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<1, ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::response() {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult& fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::response(::fuchsia_thermal::SensorManagerClearTemperatureOverrideResponse value) {
  storage_->emplace<1>(std::move(value));
  return *this;
}
::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::WithErr(::fuchsia_thermal::ClearTemperatureOverrideError val) {
  return SensorManagerClearTemperatureOverrideResult(std::make_shared<Storage_>(
      std::in_place_index_t<2>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<2, ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::err() const {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<2, ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::err() {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult& fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::err(::fuchsia_thermal::ClearTemperatureOverrideError value) {
  storage_->emplace<2>(std::move(value));
  return *this;
}
::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::WithFrameworkErr(::fidl::internal::FrameworkErr val) {
  return SensorManagerClearTemperatureOverrideResult(std::make_shared<Storage_>(
      std::in_place_index_t<3>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<3, ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::framework_err() const {
  return ::fidl::internal::UnionMemberView<3, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<3, ::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::Storage_> fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::framework_err() {
  return ::fidl::internal::UnionMemberView<3, Storage_>(storage_);
}

::fuchsia_thermal::SensorManagerClearTemperatureOverrideResult& fuchsia_thermal::SensorManagerClearTemperatureOverrideResult::framework_err(::fidl::internal::FrameworkErr value) {
  storage_->emplace<3>(std::move(value));
  return *this;
}

::fuchsia_thermal::SensorManagerConnectResult::SensorManagerConnectResult(SensorManagerConnectResult&& other) noexcept : SensorManagerConnectResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag{}) {
  *storage_ = std::move(*other.storage_);
}

::fuchsia_thermal::SensorManagerConnectResult& ::fuchsia_thermal::SensorManagerConnectResult::operator=(SensorManagerConnectResult&& other) noexcept {
  if (this != &other) {
    *storage_ = std::move(*other.storage_);
  }
  return *this;
}

::fuchsia_thermal::SensorManagerConnectResult::SensorManagerConnectResult(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag)
    : storage_(std::make_shared<Storage_>()) {}

::fuchsia_thermal::SensorManagerConnectResult::SensorManagerConnectResult(std::shared_ptr<Storage_> storage) : storage_(std::move(storage)) {}

::fuchsia_thermal::SensorManagerConnectResult::Tag fuchsia_thermal::SensorManagerConnectResult::Which() const {
  return SensorManagerConnectResult::IndexToTag(storage_->index()).value();
}

size_t fuchsia_thermal::SensorManagerConnectResult::TagToIndex(::fidl::internal::NaturalDecoder* decoder, ::fuchsia_thermal::SensorManagerConnectResult::Tag tag) {
  switch (tag) {
    case ::fuchsia_thermal::SensorManagerConnectResult::Tag::kResponse:
      return 1;
    case ::fuchsia_thermal::SensorManagerConnectResult::Tag::kErr:
      return 2;
    case ::fuchsia_thermal::SensorManagerConnectResult::Tag::kFrameworkErr:
      return 3;
    default: {
      decoder->SetError(::fidl::internal::kCodingErrorUnknownUnionTag);
      return 0;
    }
  }
}

std::optional<::fuchsia_thermal::SensorManagerConnectResult::Tag> fuchsia_thermal::SensorManagerConnectResult::IndexToTag(size_t index) {
  switch (index) {
    case 1:
      return ::fuchsia_thermal::SensorManagerConnectResult::Tag::kResponse;
    case 2:
      return ::fuchsia_thermal::SensorManagerConnectResult::Tag::kErr;
    case 3:
      return ::fuchsia_thermal::SensorManagerConnectResult::Tag::kFrameworkErr;
    default:
      return std::nullopt;
  }
}

::fuchsia_thermal::SensorManagerConnectResult::SensorManagerConnectResult(const SensorManagerConnectResult& other) noexcept : SensorManagerConnectResult(other.CloneStorage_()) {}

::fuchsia_thermal::SensorManagerConnectResult& fuchsia_thermal::SensorManagerConnectResult::operator=(const SensorManagerConnectResult& other) noexcept {
  if (this != &other) {
    storage_ = other.CloneStorage_();
  }
  return *this;
}

bool fuchsia_thermal::SensorManagerConnectResult::operator==(const SensorManagerConnectResult& other) const noexcept {
  return *storage_ == *other.storage_;
}
bool fuchsia_thermal::SensorManagerConnectResult::operator!=(const SensorManagerConnectResult& other) const noexcept {
  return *storage_ != *other.storage_;
}

std::shared_ptr<::fuchsia_thermal::SensorManagerConnectResult::Storage_> fuchsia_thermal::SensorManagerConnectResult::CloneStorage_() const {
  const Storage_& storage = *storage_;
  switch (storage_->index()) {
    case 1:
      return std::make_shared<Storage_>(
          std::in_place_index<1>,
          ::fidl::internal::NaturalClone(std::get<1>(storage)));
    case 2:
      return std::make_shared<Storage_>(
          std::in_place_index<2>,
          ::fidl::internal::NaturalClone(std::get<2>(storage)));
    case 3:
      return std::make_shared<Storage_>(
          std::in_place_index<3>,
          ::fidl::internal::NaturalClone(std::get<3>(storage)));
    default:
      return std::make_shared<Storage_>();
  }
}
::fuchsia_thermal::SensorManagerConnectResult fuchsia_thermal::SensorManagerConnectResult::WithResponse(::fuchsia_thermal::SensorManagerConnectResponse val) {
  return SensorManagerConnectResult(std::make_shared<Storage_>(
      std::in_place_index_t<1>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<1, ::fuchsia_thermal::SensorManagerConnectResult::Storage_> fuchsia_thermal::SensorManagerConnectResult::response() const {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<1, ::fuchsia_thermal::SensorManagerConnectResult::Storage_> fuchsia_thermal::SensorManagerConnectResult::response() {
  return ::fidl::internal::UnionMemberView<1, Storage_>(storage_);
}

::fuchsia_thermal::SensorManagerConnectResult& fuchsia_thermal::SensorManagerConnectResult::response(::fuchsia_thermal::SensorManagerConnectResponse value) {
  storage_->emplace<1>(std::move(value));
  return *this;
}
::fuchsia_thermal::SensorManagerConnectResult fuchsia_thermal::SensorManagerConnectResult::WithErr(::fuchsia_thermal::ConnectError val) {
  return SensorManagerConnectResult(std::make_shared<Storage_>(
      std::in_place_index_t<2>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<2, ::fuchsia_thermal::SensorManagerConnectResult::Storage_> fuchsia_thermal::SensorManagerConnectResult::err() const {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<2, ::fuchsia_thermal::SensorManagerConnectResult::Storage_> fuchsia_thermal::SensorManagerConnectResult::err() {
  return ::fidl::internal::UnionMemberView<2, Storage_>(storage_);
}

::fuchsia_thermal::SensorManagerConnectResult& fuchsia_thermal::SensorManagerConnectResult::err(::fuchsia_thermal::ConnectError value) {
  storage_->emplace<2>(std::move(value));
  return *this;
}
::fuchsia_thermal::SensorManagerConnectResult fuchsia_thermal::SensorManagerConnectResult::WithFrameworkErr(::fidl::internal::FrameworkErr val) {
  return SensorManagerConnectResult(std::make_shared<Storage_>(
      std::in_place_index_t<3>{},
      std::move(val)));
}

const ::fidl::internal::UnionMemberView<3, ::fuchsia_thermal::SensorManagerConnectResult::Storage_> fuchsia_thermal::SensorManagerConnectResult::framework_err() const {
  return ::fidl::internal::UnionMemberView<3, Storage_>(storage_);
}

::fidl::internal::UnionMemberView<3, ::fuchsia_thermal::SensorManagerConnectResult::Storage_> fuchsia_thermal::SensorManagerConnectResult::framework_err() {
  return ::fidl::internal::UnionMemberView<3, Storage_>(storage_);
}

::fuchsia_thermal::SensorManagerConnectResult& fuchsia_thermal::SensorManagerConnectResult::framework_err(::fidl::internal::FrameworkErr value) {
  storage_->emplace<3>(std::move(value));
  return *this;
}

#pragma clang diagnostic pop
