// WARNING: This file is machine generated by fidlgen.

#include <fidl/cf.sc.internal/cpp/natural_types.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wshadow"

::cf_sc_internal::Config::Config(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::cf_sc_internal::Config::Config(::std::vector<::std::string> functions) noexcept
    : storage_({.functions = std::move(functions)}) {}

::cf_sc_internal::Config::Config(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : Config(Storage_{
                                                                                                   .functions = {},
                                                                                               }) {}
::cf_sc_internal::Config::Config(const ::cf_sc_internal::Config& other) noexcept : ::cf_sc_internal::Config(other.CloneStorage_()) {}

::cf_sc_internal::Config& cf_sc_internal::Config::operator=(const ::cf_sc_internal::Config& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool cf_sc_internal::Config::operator==(const Config& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::cf_sc_internal::Config, 16>::Equal(this, &other);
}

bool cf_sc_internal::Config::operator!=(const Config& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::cf_sc_internal::Config, 16>::Equal(this, &other);
}

::cf_sc_internal::Config::Storage_ cf_sc_internal::Config::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.functions)};
}
const ::std::vector<::std::string>&
cf_sc_internal::Config::functions() const {
  return storage_.functions;
}

::std::vector<::std::string>& ::cf_sc_internal::Config::functions() {
  return storage_.functions;
}

::cf_sc_internal::Config& ::cf_sc_internal::Config::functions(::std::vector<::std::string> value) {
  storage_.functions = std::move(value);
  return *this;
}

#pragma clang diagnostic pop
