// WARNING: This file is machine generated by fidlgen.

#include <fidl/fuchsia.ldsvc/cpp/natural_types.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wshadow"

::fuchsia_ldsvc::LoaderLoadObjectRequest::LoaderLoadObjectRequest(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_ldsvc::LoaderLoadObjectRequest::LoaderLoadObjectRequest(::std::string object_name) noexcept
    : storage_({.object_name = std::move(object_name)}) {}

::fuchsia_ldsvc::LoaderLoadObjectRequest::LoaderLoadObjectRequest(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LoaderLoadObjectRequest(Storage_{
                                                                                                                                    .object_name = {},
                                                                                                                                }) {}
::fuchsia_ldsvc::LoaderLoadObjectRequest::LoaderLoadObjectRequest(const ::fuchsia_ldsvc::LoaderLoadObjectRequest& other) noexcept : ::fuchsia_ldsvc::LoaderLoadObjectRequest(other.CloneStorage_()) {}

::fuchsia_ldsvc::LoaderLoadObjectRequest& fuchsia_ldsvc::LoaderLoadObjectRequest::operator=(const ::fuchsia_ldsvc::LoaderLoadObjectRequest& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_ldsvc::LoaderLoadObjectRequest::operator==(const LoaderLoadObjectRequest& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_ldsvc::LoaderLoadObjectRequest, 16>::Equal(this, &other);
}

bool fuchsia_ldsvc::LoaderLoadObjectRequest::operator!=(const LoaderLoadObjectRequest& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_ldsvc::LoaderLoadObjectRequest, 16>::Equal(this, &other);
}

::fuchsia_ldsvc::LoaderLoadObjectRequest::Storage_ fuchsia_ldsvc::LoaderLoadObjectRequest::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.object_name)};
}
const ::std::string&
fuchsia_ldsvc::LoaderLoadObjectRequest::object_name() const {
  return storage_.object_name;
}

::std::string& ::fuchsia_ldsvc::LoaderLoadObjectRequest::object_name() {
  return storage_.object_name;
}

::fuchsia_ldsvc::LoaderLoadObjectRequest& ::fuchsia_ldsvc::LoaderLoadObjectRequest::object_name(::std::string value) {
  storage_.object_name = std::move(value);
  return *this;
}
#if __FIDL_SUPPORT_HANDLES

::fuchsia_ldsvc::LoaderLoadObjectResponse::LoaderLoadObjectResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_ldsvc::LoaderLoadObjectResponse::LoaderLoadObjectResponse(int32_t rv, ::zx::vmo object) noexcept
    : storage_({.rv = std::move(rv),
                .object = std::move(object)}) {}

::fuchsia_ldsvc::LoaderLoadObjectResponse::LoaderLoadObjectResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LoaderLoadObjectResponse(Storage_{
                                                                                                                                      .rv = {},
                                                                                                                                      .object = {},
                                                                                                                                  }) {}
int32_t
fuchsia_ldsvc::LoaderLoadObjectResponse::rv() const {
  return storage_.rv;
}

int32_t& ::fuchsia_ldsvc::LoaderLoadObjectResponse::rv() {
  return storage_.rv;
}

::fuchsia_ldsvc::LoaderLoadObjectResponse& ::fuchsia_ldsvc::LoaderLoadObjectResponse::rv(int32_t value) {
  storage_.rv = std::move(value);
  return *this;
}
const ::zx::vmo&
fuchsia_ldsvc::LoaderLoadObjectResponse::object() const {
  return storage_.object;
}

::zx::vmo& ::fuchsia_ldsvc::LoaderLoadObjectResponse::object() {
  return storage_.object;
}

::fuchsia_ldsvc::LoaderLoadObjectResponse& ::fuchsia_ldsvc::LoaderLoadObjectResponse::object(::zx::vmo value) {
  storage_.object = std::move(value);
  return *this;
}

#endif  // __FIDL_SUPPORT_HANDLES

::fuchsia_ldsvc::LoaderConfigRequest::LoaderConfigRequest(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_ldsvc::LoaderConfigRequest::LoaderConfigRequest(::std::string config) noexcept
    : storage_({.config = std::move(config)}) {}

::fuchsia_ldsvc::LoaderConfigRequest::LoaderConfigRequest(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LoaderConfigRequest(Storage_{
                                                                                                                            .config = {},
                                                                                                                        }) {}
::fuchsia_ldsvc::LoaderConfigRequest::LoaderConfigRequest(const ::fuchsia_ldsvc::LoaderConfigRequest& other) noexcept : ::fuchsia_ldsvc::LoaderConfigRequest(other.CloneStorage_()) {}

::fuchsia_ldsvc::LoaderConfigRequest& fuchsia_ldsvc::LoaderConfigRequest::operator=(const ::fuchsia_ldsvc::LoaderConfigRequest& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_ldsvc::LoaderConfigRequest::operator==(const LoaderConfigRequest& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_ldsvc::LoaderConfigRequest, 16>::Equal(this, &other);
}

bool fuchsia_ldsvc::LoaderConfigRequest::operator!=(const LoaderConfigRequest& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_ldsvc::LoaderConfigRequest, 16>::Equal(this, &other);
}

::fuchsia_ldsvc::LoaderConfigRequest::Storage_ fuchsia_ldsvc::LoaderConfigRequest::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.config)};
}
const ::std::string&
fuchsia_ldsvc::LoaderConfigRequest::config() const {
  return storage_.config;
}

::std::string& ::fuchsia_ldsvc::LoaderConfigRequest::config() {
  return storage_.config;
}

::fuchsia_ldsvc::LoaderConfigRequest& ::fuchsia_ldsvc::LoaderConfigRequest::config(::std::string value) {
  storage_.config = std::move(value);
  return *this;
}

::fuchsia_ldsvc::LoaderConfigResponse::LoaderConfigResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_ldsvc::LoaderConfigResponse::LoaderConfigResponse(int32_t rv) noexcept
    : storage_({.rv = std::move(rv)}) {}

::fuchsia_ldsvc::LoaderConfigResponse::LoaderConfigResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LoaderConfigResponse(Storage_{
                                                                                                                              .rv = {},
                                                                                                                          }) {}
::fuchsia_ldsvc::LoaderConfigResponse::LoaderConfigResponse(const ::fuchsia_ldsvc::LoaderConfigResponse& other) noexcept : ::fuchsia_ldsvc::LoaderConfigResponse(other.CloneStorage_()) {}

::fuchsia_ldsvc::LoaderConfigResponse& fuchsia_ldsvc::LoaderConfigResponse::operator=(const ::fuchsia_ldsvc::LoaderConfigResponse& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_ldsvc::LoaderConfigResponse::operator==(const LoaderConfigResponse& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_ldsvc::LoaderConfigResponse, 4>::Equal(this, &other);
}

bool fuchsia_ldsvc::LoaderConfigResponse::operator!=(const LoaderConfigResponse& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_ldsvc::LoaderConfigResponse, 4>::Equal(this, &other);
}

::fuchsia_ldsvc::LoaderConfigResponse::Storage_ fuchsia_ldsvc::LoaderConfigResponse::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.rv)};
}
int32_t
fuchsia_ldsvc::LoaderConfigResponse::rv() const {
  return storage_.rv;
}

int32_t& ::fuchsia_ldsvc::LoaderConfigResponse::rv() {
  return storage_.rv;
}

::fuchsia_ldsvc::LoaderConfigResponse& ::fuchsia_ldsvc::LoaderConfigResponse::rv(int32_t value) {
  storage_.rv = std::move(value);
  return *this;
}
#if __FIDL_SUPPORT_HANDLES

::fuchsia_ldsvc::LoaderCloneRequest::LoaderCloneRequest(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_ldsvc::LoaderCloneRequest::LoaderCloneRequest(::fidl::ServerEnd<::fuchsia_ldsvc::Loader> loader) noexcept
    : storage_({.loader = std::move(loader)}) {}

::fuchsia_ldsvc::LoaderCloneRequest::LoaderCloneRequest(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LoaderCloneRequest(Storage_{
                                                                                                                          .loader = {},
                                                                                                                      }) {}
const ::fidl::ServerEnd<::fuchsia_ldsvc::Loader>&
fuchsia_ldsvc::LoaderCloneRequest::loader() const {
  return storage_.loader;
}

::fidl::ServerEnd<::fuchsia_ldsvc::Loader>& ::fuchsia_ldsvc::LoaderCloneRequest::loader() {
  return storage_.loader;
}

::fuchsia_ldsvc::LoaderCloneRequest& ::fuchsia_ldsvc::LoaderCloneRequest::loader(::fidl::ServerEnd<::fuchsia_ldsvc::Loader> value) {
  storage_.loader = std::move(value);
  return *this;
}

#endif  // __FIDL_SUPPORT_HANDLES

::fuchsia_ldsvc::LoaderCloneResponse::LoaderCloneResponse(Storage_ storage) noexcept : storage_(std::move(storage)) {}
::fuchsia_ldsvc::LoaderCloneResponse::LoaderCloneResponse(int32_t rv) noexcept
    : storage_({.rv = std::move(rv)}) {}

::fuchsia_ldsvc::LoaderCloneResponse::LoaderCloneResponse(::fidl::internal::DefaultConstructPossiblyInvalidObjectTag) : LoaderCloneResponse(Storage_{
                                                                                                                            .rv = {},
                                                                                                                        }) {}
::fuchsia_ldsvc::LoaderCloneResponse::LoaderCloneResponse(const ::fuchsia_ldsvc::LoaderCloneResponse& other) noexcept : ::fuchsia_ldsvc::LoaderCloneResponse(other.CloneStorage_()) {}

::fuchsia_ldsvc::LoaderCloneResponse& fuchsia_ldsvc::LoaderCloneResponse::operator=(const ::fuchsia_ldsvc::LoaderCloneResponse& other) noexcept {
  storage_ = other.CloneStorage_();
  return *this;
}

bool fuchsia_ldsvc::LoaderCloneResponse::operator==(const LoaderCloneResponse& other) const noexcept {
  return ::fidl::internal::NaturalStructCodingTraits<::fuchsia_ldsvc::LoaderCloneResponse, 4>::Equal(this, &other);
}

bool fuchsia_ldsvc::LoaderCloneResponse::operator!=(const LoaderCloneResponse& other) const noexcept {
  return !::fidl::internal::NaturalStructCodingTraits<::fuchsia_ldsvc::LoaderCloneResponse, 4>::Equal(this, &other);
}

::fuchsia_ldsvc::LoaderCloneResponse::Storage_ fuchsia_ldsvc::LoaderCloneResponse::CloneStorage_() const {
  return Storage_{
      ::fidl::internal::NaturalClone(storage_.rv)};
}
int32_t
fuchsia_ldsvc::LoaderCloneResponse::rv() const {
  return storage_.rv;
}

int32_t& ::fuchsia_ldsvc::LoaderCloneResponse::rv() {
  return storage_.rv;
}

::fuchsia_ldsvc::LoaderCloneResponse& ::fuchsia_ldsvc::LoaderCloneResponse::rv(int32_t value) {
  storage_.rv = std::move(value);
  return *this;
}

#pragma clang diagnostic pop
